# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.srcs/my_rm/bd/ulp/ip/ulp_s00_regslice_39/ulp_s00_regslice_39.xci
# IP: The module: 'ulp_s00_regslice_39' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_s00_regslice_39/ulp_s00_regslice_39_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp_s00_regslice_39'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_s00_regslice_39/ulp_s00_regslice_39_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp_s00_regslice_39'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.srcs/my_rm/bd/ulp/ip/ulp_s00_regslice_39/ulp_s00_regslice_39.xci
# IP: The module: 'ulp_s00_regslice_39' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_s00_regslice_39/ulp_s00_regslice_39_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp_s00_regslice_39'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_s00_regslice_39/ulp_s00_regslice_39_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp_s00_regslice_39'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
