# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_90/bd_1361_clock_throttling_aclk_kernel_01_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_1361_clock_throttling_aclk_kernel_01_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_90/bd_1361_clock_throttling_aclk_kernel_01_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_1361_clock_throttling_aclk_kernel_01_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_90/bd_1361_clock_throttling_aclk_kernel_01_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_1361_clock_throttling_aclk_kernel_01_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_90/bd_1361_clock_throttling_aclk_kernel_01_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_1361_clock_throttling_aclk_kernel_01_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
