log_wave -quiet /pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/topKQueryScores_1/inst/ap_idle
get_value_database /pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/topKQueryScores_1/inst/ap_idle -time 0 -quiet 

log_wave -quiet /pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/topKQueryScores_1/inst/ap_int_blocking_n
get_value_database /pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/topKQueryScores_1/inst/ap_int_blocking_n -time 0 -quiet 

log_wave -quiet /pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/topKQueryScores_1/inst/ap_ext_blocking_n
get_value_database /pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/topKQueryScores_1/inst/ap_ext_blocking_n -time 0 -quiet 

log_wave -quiet /pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/topKQueryScores_1/inst/ap_str_blocking_n
get_value_database /pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/topKQueryScores_1/inst/ap_str_blocking_n -time 0 -quiet 

log_wave -quiet /pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/topKQueryScores_1/inst/grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154/ap_idle
get_value_database /pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/topKQueryScores_1/inst/grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154/ap_idle -time 0 -quiet 

log_wave -quiet /pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/topKQueryScores_1/inst/grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154/ap_int_blocking_n
get_value_database /pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/topKQueryScores_1/inst/grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154/ap_int_blocking_n -time 0 -quiet 

log_wave -quiet /pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/topKQueryScores_1/inst/grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154/ap_ext_blocking_n
get_value_database /pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/topKQueryScores_1/inst/grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154/ap_ext_blocking_n -time 0 -quiet 

log_wave -quiet /pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/topKQueryScores_1/inst/grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154/ap_str_blocking_n
get_value_database /pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/topKQueryScores_1/inst/grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154/ap_str_blocking_n -time 0 -quiet 

log_wave -quiet /pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/topKQueryScores_1/inst/grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165/ap_idle
get_value_database /pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/topKQueryScores_1/inst/grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165/ap_idle -time 0 -quiet 

log_wave -quiet /pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/topKQueryScores_1/inst/grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165/ap_int_blocking_n
get_value_database /pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/topKQueryScores_1/inst/grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165/ap_int_blocking_n -time 0 -quiet 

log_wave -quiet /pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/topKQueryScores_1/inst/grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165/ap_ext_blocking_n
get_value_database /pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/topKQueryScores_1/inst/grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165/ap_ext_blocking_n -time 0 -quiet 

log_wave -quiet /pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/topKQueryScores_1/inst/grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165/ap_str_blocking_n
get_value_database /pfm_top_wrapper/pfm_top_i/pfm_dynamic_inst/topKQueryScores_1/inst/grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165/ap_str_blocking_n -time 0 -quiet 

