#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Nov 27 17:41:41 PST 2023
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail

export xv_cxl_lib_path="/tools/Xilinx/Vivado/2022.2/data/xsim"
export xv_cxl_ip_path="$xv_cxl_lib_path/ip"
export xv_cpt_lib_path="/tools/Xilinx/Vivado/2022.2/data/simmodels/xsim/2022.2/lnx64/6.2.0/systemc/protected"
xv_ext_lib_path="/tools/Xilinx/Vivado/2022.2/data/simmodels/xsim/2022.2/lnx64/6.2.0/ext"
xv_lib_path="/tools/Xilinx/Vivado/2022.2/lib/lnx64.o/Default:/tools/Xilinx/Vivado/2022.2/lib/lnx64.o"

xv_ref_path=${VIVADO_LOC:-"/tools/Xilinx/Vivado/2022.2"}
xv_lib_path="$xv_ref_path/lib/lnx64.o/Default:$xv_ref_path/lib/lnx64.o"

export LD_LIBRARY_PATH=$PWD:$xv_lib_path:$xv_ref_path/data/simmodels/xsim/2022.2/lnx64/6.2.0/ext/protobuf:$xv_ref_path/data/xsim/ip/xscl:$xv_ref_path/data/xsim/ip/sim_qdma_cpp_v1_0:$xv_ref_path/data/xsim/ip/xtlm_ipc_v1_0:$xv_ref_path/data/xsim/ip/sim_qdma_sc_v1_0:$xv_ref_path/data/xsim/ip/xtlm_simple_interconnect_v1_0:$xv_ref_path/data/xsim/ip/xtlm_ap_ctrl_v1_0:$xv_ref_path/data/xsim/ip/sim_ddr_v1_0:$xv_ref_path/data/xsim/ip/common_cpp_v1_0:$xv_ref_path/data/xsim/ip/common_rpc_v1:$xv_ref_path/data/xsim/ip/xtlm:$xv_ref_path/data/xsim/ip/emu_perf_common_v1_0:$LD_LIBRARY_PATH

# simulate design
echo "xsim pfm_top_wrapper_behav -key {Behavioral:sim_1:Functional:pfm_top_wrapper} -tclbatch pfm_top_wrapper.tcl -protoinst "protoinst_files/bd_f615.protoinst" -protoinst "protoinst_files/bd_2b97.protoinst" -protoinst "protoinst_files/bd_d216.protoinst" -protoinst "protoinst_files/pfm_dynamic.protoinst" -protoinst "protoinst_files/bd_448f.protoinst" -protoinst "protoinst_files/bd_387c.protoinst" -protoinst "protoinst_files/pfm_top.protoinst" -log simulate.log $*"
xsim pfm_top_wrapper_behav -key {Behavioral:sim_1:Functional:pfm_top_wrapper} -tclbatch pfm_top_wrapper.tcl -protoinst "protoinst_files/bd_f615.protoinst" -protoinst "protoinst_files/bd_2b97.protoinst" -protoinst "protoinst_files/bd_d216.protoinst" -protoinst "protoinst_files/pfm_dynamic.protoinst" -protoinst "protoinst_files/bd_448f.protoinst" -protoinst "protoinst_files/bd_387c.protoinst" -protoinst "protoinst_files/pfm_top.protoinst" -log simulate.log $*

