# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ulp/ulp.bd
# Block Designs: The module: 'ulp' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: bd/ulp/ip/ulp_ii_level1_wire_0/ulp_ii_level1_wire_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ii_level1_wire_0 || ORIG_REF_NAME==ulp_ii_level1_wire_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_memory_subsystem_0/ulp_memory_subsystem_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_memory_subsystem_0 || ORIG_REF_NAME==ulp_memory_subsystem_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ss_ucs_0/ulp_ss_ucs_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ss_ucs_0 || ORIG_REF_NAME==ulp_ss_ucs_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_cc_axi_data_h2c_00_0/ulp_ip_cc_axi_data_h2c_00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_cc_axi_data_h2c_00_0 || ORIG_REF_NAME==ulp_ip_cc_axi_data_h2c_00_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_cc_axi_data_h2c_01_0/ulp_ip_cc_axi_data_h2c_01_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_cc_axi_data_h2c_01_0 || ORIG_REF_NAME==ulp_ip_cc_axi_data_h2c_01_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_cc_axi_data_h2c_02_0/ulp_ip_cc_axi_data_h2c_02_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_cc_axi_data_h2c_02_0 || ORIG_REF_NAME==ulp_ip_cc_axi_data_h2c_02_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_cc_axi_data_h2c_03_0/ulp_ip_cc_axi_data_h2c_03_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_cc_axi_data_h2c_03_0 || ORIG_REF_NAME==ulp_ip_cc_axi_data_h2c_03_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_rs_axi_data_h2c_03_0/ulp_ip_rs_axi_data_h2c_03_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_rs_axi_data_h2c_03_0 || ORIG_REF_NAME==ulp_ip_rs_axi_data_h2c_03_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_rs_axi_ctrl_user_03_0/ulp_ip_rs_axi_ctrl_user_03_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_rs_axi_ctrl_user_03_0 || ORIG_REF_NAME==ulp_ip_rs_axi_ctrl_user_03_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_rs_axi_data_c2h_00_0/ulp_ip_rs_axi_data_c2h_00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_rs_axi_data_c2h_00_0 || ORIG_REF_NAME==ulp_ip_rs_axi_data_c2h_00_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ict_axi_ctrl_mgmt_00_0/ulp_ict_axi_ctrl_mgmt_00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ict_axi_ctrl_mgmt_00_0 || ORIG_REF_NAME==ulp_ict_axi_ctrl_mgmt_00_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ict_axi_ctrl_mgmt_01_0/ulp_ict_axi_ctrl_mgmt_01_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ict_axi_ctrl_mgmt_01_0 || ORIG_REF_NAME==ulp_ict_axi_ctrl_mgmt_01_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ict_axi_ctrl_user_00_0/ulp_ict_axi_ctrl_user_00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ict_axi_ctrl_user_00_0 || ORIG_REF_NAME==ulp_ict_axi_ctrl_user_00_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ict_axi_ctrl_user_01_0/ulp_ict_axi_ctrl_user_01_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ict_axi_ctrl_user_01_0 || ORIG_REF_NAME==ulp_ict_axi_ctrl_user_01_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ict_axi_ctrl_user_02_0/ulp_ict_axi_ctrl_user_02_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ict_axi_ctrl_user_02_0 || ORIG_REF_NAME==ulp_ict_axi_ctrl_user_02_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ict_axi_ctrl_user_03_0/ulp_ict_axi_ctrl_user_03_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ict_axi_ctrl_user_03_0 || ORIG_REF_NAME==ulp_ict_axi_ctrl_user_03_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ict_axi_ctrl_user_debug_00_0/ulp_ict_axi_ctrl_user_debug_00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ict_axi_ctrl_user_debug_00_0 || ORIG_REF_NAME==ulp_ict_axi_ctrl_user_debug_00_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_shell_cmp_subsystem_0_0/ulp_shell_cmp_subsystem_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_shell_cmp_subsystem_0_0 || ORIG_REF_NAME==ulp_shell_cmp_subsystem_0_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_mgmt_00_0/ulp_ip_gpio_debug_axi_ctrl_mgmt_00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_gpio_debug_axi_ctrl_mgmt_00_0 || ORIG_REF_NAME==ulp_ip_gpio_debug_axi_ctrl_mgmt_00_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_mgmt_01_0/ulp_ip_gpio_debug_axi_ctrl_mgmt_01_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_gpio_debug_axi_ctrl_mgmt_01_0 || ORIG_REF_NAME==ulp_ip_gpio_debug_axi_ctrl_mgmt_01_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_user_00_0/ulp_ip_gpio_debug_axi_ctrl_user_00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_gpio_debug_axi_ctrl_user_00_0 || ORIG_REF_NAME==ulp_ip_gpio_debug_axi_ctrl_user_00_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_user_01_0/ulp_ip_gpio_debug_axi_ctrl_user_01_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_gpio_debug_axi_ctrl_user_01_0 || ORIG_REF_NAME==ulp_ip_gpio_debug_axi_ctrl_user_01_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_user_02_0/ulp_ip_gpio_debug_axi_ctrl_user_02_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_gpio_debug_axi_ctrl_user_02_0 || ORIG_REF_NAME==ulp_ip_gpio_debug_axi_ctrl_user_02_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_user_03_0/ulp_ip_gpio_debug_axi_ctrl_user_03_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_gpio_debug_axi_ctrl_user_03_0 || ORIG_REF_NAME==ulp_ip_gpio_debug_axi_ctrl_user_03_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_user_debug_00_0/ulp_ip_gpio_debug_axi_ctrl_user_debug_00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_gpio_debug_axi_ctrl_user_debug_00_0 || ORIG_REF_NAME==ulp_ip_gpio_debug_axi_ctrl_user_debug_00_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_inv_aresetn_ctrl_00_0/ulp_ip_inv_aresetn_ctrl_00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_inv_aresetn_ctrl_00_0 || ORIG_REF_NAME==ulp_ip_inv_aresetn_ctrl_00_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ict_axi_data_h2c_01_0/ulp_ict_axi_data_h2c_01_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ict_axi_data_h2c_01_0 || ORIG_REF_NAME==ulp_ict_axi_data_h2c_01_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_gpio_debug_axi_data_h2c_01_0/ulp_ip_gpio_debug_axi_data_h2c_01_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_gpio_debug_axi_data_h2c_01_0 || ORIG_REF_NAME==ulp_ip_gpio_debug_axi_data_h2c_01_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_psr_aresetn_ctrl_slr0_0/ulp_ip_psr_aresetn_ctrl_slr0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_psr_aresetn_ctrl_slr0_0 || ORIG_REF_NAME==ulp_ip_psr_aresetn_ctrl_slr0_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_psr_aresetn_ctrl_slr1_0/ulp_ip_psr_aresetn_ctrl_slr1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_psr_aresetn_ctrl_slr1_0 || ORIG_REF_NAME==ulp_ip_psr_aresetn_ctrl_slr1_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_psr_aresetn_ctrl_slr2_0/ulp_ip_psr_aresetn_ctrl_slr2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_psr_aresetn_ctrl_slr2_0 || ORIG_REF_NAME==ulp_ip_psr_aresetn_ctrl_slr2_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_psr_aresetn_ctrl_slr3_0/ulp_ip_psr_aresetn_ctrl_slr3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_psr_aresetn_ctrl_slr3_0 || ORIG_REF_NAME==ulp_ip_psr_aresetn_ctrl_slr3_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_psr_aresetn_kernel_00_slr0_0/ulp_ip_psr_aresetn_kernel_00_slr0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_psr_aresetn_kernel_00_slr0_0 || ORIG_REF_NAME==ulp_ip_psr_aresetn_kernel_00_slr0_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_psr_aresetn_kernel_00_slr1_0/ulp_ip_psr_aresetn_kernel_00_slr1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_psr_aresetn_kernel_00_slr1_0 || ORIG_REF_NAME==ulp_ip_psr_aresetn_kernel_00_slr1_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_psr_aresetn_kernel_00_slr2_0/ulp_ip_psr_aresetn_kernel_00_slr2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_psr_aresetn_kernel_00_slr2_0 || ORIG_REF_NAME==ulp_ip_psr_aresetn_kernel_00_slr2_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_psr_aresetn_kernel_00_slr3_0/ulp_ip_psr_aresetn_kernel_00_slr3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_psr_aresetn_kernel_00_slr3_0 || ORIG_REF_NAME==ulp_ip_psr_aresetn_kernel_00_slr3_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_psr_aresetn_kernel_01_slr0_0/ulp_ip_psr_aresetn_kernel_01_slr0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_psr_aresetn_kernel_01_slr0_0 || ORIG_REF_NAME==ulp_ip_psr_aresetn_kernel_01_slr0_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_psr_aresetn_kernel_01_slr1_0/ulp_ip_psr_aresetn_kernel_01_slr1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_psr_aresetn_kernel_01_slr1_0 || ORIG_REF_NAME==ulp_ip_psr_aresetn_kernel_01_slr1_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_psr_aresetn_kernel_01_slr2_0/ulp_ip_psr_aresetn_kernel_01_slr2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_psr_aresetn_kernel_01_slr2_0 || ORIG_REF_NAME==ulp_ip_psr_aresetn_kernel_01_slr2_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_psr_aresetn_kernel_01_slr3_0/ulp_ip_psr_aresetn_kernel_01_slr3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_psr_aresetn_kernel_01_slr3_0 || ORIG_REF_NAME==ulp_ip_psr_aresetn_kernel_01_slr3_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_psr_aresetn_pcie_slr0_0/ulp_ip_psr_aresetn_pcie_slr0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_psr_aresetn_pcie_slr0_0 || ORIG_REF_NAME==ulp_ip_psr_aresetn_pcie_slr0_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_psr_aresetn_pcie_slr1_0/ulp_ip_psr_aresetn_pcie_slr1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_psr_aresetn_pcie_slr1_0 || ORIG_REF_NAME==ulp_ip_psr_aresetn_pcie_slr1_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_psr_aresetn_pcie_slr2_0/ulp_ip_psr_aresetn_pcie_slr2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_psr_aresetn_pcie_slr2_0 || ORIG_REF_NAME==ulp_ip_psr_aresetn_pcie_slr2_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_psr_aresetn_pcie_slr3_0/ulp_ip_psr_aresetn_pcie_slr3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_psr_aresetn_pcie_slr3_0 || ORIG_REF_NAME==ulp_ip_psr_aresetn_pcie_slr3_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_psr_aresetn_freerun_slr0_0/ulp_ip_psr_aresetn_freerun_slr0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_psr_aresetn_freerun_slr0_0 || ORIG_REF_NAME==ulp_ip_psr_aresetn_freerun_slr0_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_psr_aresetn_freerun_slr1_0/ulp_ip_psr_aresetn_freerun_slr1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_psr_aresetn_freerun_slr1_0 || ORIG_REF_NAME==ulp_ip_psr_aresetn_freerun_slr1_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_psr_aresetn_freerun_slr2_0/ulp_ip_psr_aresetn_freerun_slr2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_psr_aresetn_freerun_slr2_0 || ORIG_REF_NAME==ulp_ip_psr_aresetn_freerun_slr2_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_psr_aresetn_freerun_slr3_0/ulp_ip_psr_aresetn_freerun_slr3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_psr_aresetn_freerun_slr3_0 || ORIG_REF_NAME==ulp_ip_psr_aresetn_freerun_slr3_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_satellite_gpio_slice_1_0/ulp_satellite_gpio_slice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_satellite_gpio_slice_1_0 || ORIG_REF_NAME==ulp_satellite_gpio_slice_1_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_xbar_2/ulp_xbar_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_xbar_2 || ORIG_REF_NAME==ulp_xbar_2} -quiet] -quiet

# IP: bd/ulp/ip/ulp_xbar_3/ulp_xbar_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_xbar_3 || ORIG_REF_NAME==ulp_xbar_3} -quiet] -quiet

# IP: bd/ulp/ip/ulp_xbar_4/ulp_xbar_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_xbar_4 || ORIG_REF_NAME==ulp_xbar_4} -quiet] -quiet

# IP: bd/ulp/ip/ulp_topKQueryScores_1_0/ulp_topKQueryScores_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_topKQueryScores_1_0 || ORIG_REF_NAME==ulp_topKQueryScores_1_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ii_level1_wire_ulp_s_irq_kernel_00_1_interrupt_concat_0/ulp_ii_level1_wire_ulp_s_irq_kernel_00_1_interrupt_concat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ii_level1_wire_ulp_s_irq_kernel_00_1_interrupt_concat_0 || ORIG_REF_NAME==ulp_ii_level1_wire_ulp_s_irq_kernel_00_1_interrupt_concat_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ii_level1_wire_ulp_s_irq_kernel_00_1_interrupt_concat_0_0/ulp_ii_level1_wire_ulp_s_irq_kernel_00_1_interrupt_concat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ii_level1_wire_ulp_s_irq_kernel_00_1_interrupt_concat_0_0 || ORIG_REF_NAME==ulp_ii_level1_wire_ulp_s_irq_kernel_00_1_interrupt_concat_0_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ii_level1_wire_ulp_s_irq_kernel_00_1_interrupt_concat_1_0/ulp_ii_level1_wire_ulp_s_irq_kernel_00_1_interrupt_concat_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ii_level1_wire_ulp_s_irq_kernel_00_1_interrupt_concat_1_0 || ORIG_REF_NAME==ulp_ii_level1_wire_ulp_s_irq_kernel_00_1_interrupt_concat_1_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ii_level1_wire_ulp_s_irq_kernel_00_1_interrupt_concat_2_0/ulp_ii_level1_wire_ulp_s_irq_kernel_00_1_interrupt_concat_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ii_level1_wire_ulp_s_irq_kernel_00_1_interrupt_concat_2_0 || ORIG_REF_NAME==ulp_ii_level1_wire_ulp_s_irq_kernel_00_1_interrupt_concat_2_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ii_level1_wire_ulp_s_irq_kernel_00_1_interrupt_concat_3_0/ulp_ii_level1_wire_ulp_s_irq_kernel_00_1_interrupt_concat_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ii_level1_wire_ulp_s_irq_kernel_00_1_interrupt_concat_3_0 || ORIG_REF_NAME==ulp_ii_level1_wire_ulp_s_irq_kernel_00_1_interrupt_concat_3_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_irq_const_tieoff_0/ulp_irq_const_tieoff_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_irq_const_tieoff_0 || ORIG_REF_NAME==ulp_irq_const_tieoff_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_s00_regslice_38/ulp_s00_regslice_38.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_s00_regslice_38 || ORIG_REF_NAME==ulp_s00_regslice_38} -quiet] -quiet

# IP: bd/ulp/ip/ulp_s00_regslice_39/ulp_s00_regslice_39.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_s00_regslice_39 || ORIG_REF_NAME==ulp_s00_regslice_39} -quiet] -quiet

# IP: bd/ulp/ip/ulp_m00_regslice_2/ulp_m00_regslice_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_m00_regslice_2 || ORIG_REF_NAME==ulp_m00_regslice_2} -quiet] -quiet

# IP: bd/ulp/ip/ulp_m01_regslice_2/ulp_m01_regslice_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_m01_regslice_2 || ORIG_REF_NAME==ulp_m01_regslice_2} -quiet] -quiet

# IP: bd/ulp/ip/ulp_m02_regslice_0/ulp_m02_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_m02_regslice_0 || ORIG_REF_NAME==ulp_m02_regslice_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_m03_regslice_0/ulp_m03_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_m03_regslice_0 || ORIG_REF_NAME==ulp_m03_regslice_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_s00_regslice_40/ulp_s00_regslice_40.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_s00_regslice_40 || ORIG_REF_NAME==ulp_s00_regslice_40} -quiet] -quiet

# IP: bd/ulp/ip/ulp_s00_regslice_41/ulp_s00_regslice_41.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_s00_regslice_41 || ORIG_REF_NAME==ulp_s00_regslice_41} -quiet] -quiet

# IP: bd/ulp/ip/ulp_m00_regslice_3/ulp_m00_regslice_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_m00_regslice_3 || ORIG_REF_NAME==ulp_m00_regslice_3} -quiet] -quiet

# IP: bd/ulp/ip/ulp_m01_regslice_3/ulp_m01_regslice_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_m01_regslice_3 || ORIG_REF_NAME==ulp_m01_regslice_3} -quiet] -quiet

# IP: bd/ulp/ip/ulp_auto_cc_0/ulp_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_auto_cc_0 || ORIG_REF_NAME==ulp_auto_cc_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_s00_regslice_42/ulp_s00_regslice_42.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_s00_regslice_42 || ORIG_REF_NAME==ulp_s00_regslice_42} -quiet] -quiet

# IP: bd/ulp/ip/ulp_s00_regslice_43/ulp_s00_regslice_43.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_s00_regslice_43 || ORIG_REF_NAME==ulp_s00_regslice_43} -quiet] -quiet

# IP: bd/ulp/ip/ulp_s00_regslice_44/ulp_s00_regslice_44.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_s00_regslice_44 || ORIG_REF_NAME==ulp_s00_regslice_44} -quiet] -quiet

# IP: bd/ulp/ip/ulp_s00_regslice_45/ulp_s00_regslice_45.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_s00_regslice_45 || ORIG_REF_NAME==ulp_s00_regslice_45} -quiet] -quiet

# IP: bd/ulp/ip/ulp_auto_ds_0/ulp_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_auto_ds_0 || ORIG_REF_NAME==ulp_auto_ds_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_auto_pc_0/ulp_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_auto_pc_0 || ORIG_REF_NAME==ulp_auto_pc_0} -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ulp_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp'. Do not add the DONT_TOUCH constraint.

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/output/ulp_ooc_copy.xdc

# Block Designs: bd/ulp/ulp.bd
# Block Designs: The module: 'ulp' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: bd/ulp/ip/ulp_ii_level1_wire_0/ulp_ii_level1_wire_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ii_level1_wire_0 || ORIG_REF_NAME==ulp_ii_level1_wire_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_memory_subsystem_0/ulp_memory_subsystem_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_memory_subsystem_0 || ORIG_REF_NAME==ulp_memory_subsystem_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ss_ucs_0/ulp_ss_ucs_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ss_ucs_0 || ORIG_REF_NAME==ulp_ss_ucs_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_cc_axi_data_h2c_00_0/ulp_ip_cc_axi_data_h2c_00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_cc_axi_data_h2c_00_0 || ORIG_REF_NAME==ulp_ip_cc_axi_data_h2c_00_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_cc_axi_data_h2c_01_0/ulp_ip_cc_axi_data_h2c_01_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_cc_axi_data_h2c_01_0 || ORIG_REF_NAME==ulp_ip_cc_axi_data_h2c_01_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_cc_axi_data_h2c_02_0/ulp_ip_cc_axi_data_h2c_02_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_cc_axi_data_h2c_02_0 || ORIG_REF_NAME==ulp_ip_cc_axi_data_h2c_02_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_cc_axi_data_h2c_03_0/ulp_ip_cc_axi_data_h2c_03_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_cc_axi_data_h2c_03_0 || ORIG_REF_NAME==ulp_ip_cc_axi_data_h2c_03_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_rs_axi_data_h2c_03_0/ulp_ip_rs_axi_data_h2c_03_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_rs_axi_data_h2c_03_0 || ORIG_REF_NAME==ulp_ip_rs_axi_data_h2c_03_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_rs_axi_ctrl_user_03_0/ulp_ip_rs_axi_ctrl_user_03_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_rs_axi_ctrl_user_03_0 || ORIG_REF_NAME==ulp_ip_rs_axi_ctrl_user_03_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_rs_axi_data_c2h_00_0/ulp_ip_rs_axi_data_c2h_00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_rs_axi_data_c2h_00_0 || ORIG_REF_NAME==ulp_ip_rs_axi_data_c2h_00_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ict_axi_ctrl_mgmt_00_0/ulp_ict_axi_ctrl_mgmt_00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ict_axi_ctrl_mgmt_00_0 || ORIG_REF_NAME==ulp_ict_axi_ctrl_mgmt_00_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ict_axi_ctrl_mgmt_01_0/ulp_ict_axi_ctrl_mgmt_01_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ict_axi_ctrl_mgmt_01_0 || ORIG_REF_NAME==ulp_ict_axi_ctrl_mgmt_01_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ict_axi_ctrl_user_00_0/ulp_ict_axi_ctrl_user_00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ict_axi_ctrl_user_00_0 || ORIG_REF_NAME==ulp_ict_axi_ctrl_user_00_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ict_axi_ctrl_user_01_0/ulp_ict_axi_ctrl_user_01_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ict_axi_ctrl_user_01_0 || ORIG_REF_NAME==ulp_ict_axi_ctrl_user_01_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ict_axi_ctrl_user_02_0/ulp_ict_axi_ctrl_user_02_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ict_axi_ctrl_user_02_0 || ORIG_REF_NAME==ulp_ict_axi_ctrl_user_02_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ict_axi_ctrl_user_03_0/ulp_ict_axi_ctrl_user_03_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ict_axi_ctrl_user_03_0 || ORIG_REF_NAME==ulp_ict_axi_ctrl_user_03_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ict_axi_ctrl_user_debug_00_0/ulp_ict_axi_ctrl_user_debug_00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ict_axi_ctrl_user_debug_00_0 || ORIG_REF_NAME==ulp_ict_axi_ctrl_user_debug_00_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_shell_cmp_subsystem_0_0/ulp_shell_cmp_subsystem_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_shell_cmp_subsystem_0_0 || ORIG_REF_NAME==ulp_shell_cmp_subsystem_0_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_mgmt_00_0/ulp_ip_gpio_debug_axi_ctrl_mgmt_00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_gpio_debug_axi_ctrl_mgmt_00_0 || ORIG_REF_NAME==ulp_ip_gpio_debug_axi_ctrl_mgmt_00_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_mgmt_01_0/ulp_ip_gpio_debug_axi_ctrl_mgmt_01_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_gpio_debug_axi_ctrl_mgmt_01_0 || ORIG_REF_NAME==ulp_ip_gpio_debug_axi_ctrl_mgmt_01_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_user_00_0/ulp_ip_gpio_debug_axi_ctrl_user_00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_gpio_debug_axi_ctrl_user_00_0 || ORIG_REF_NAME==ulp_ip_gpio_debug_axi_ctrl_user_00_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_user_01_0/ulp_ip_gpio_debug_axi_ctrl_user_01_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_gpio_debug_axi_ctrl_user_01_0 || ORIG_REF_NAME==ulp_ip_gpio_debug_axi_ctrl_user_01_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_user_02_0/ulp_ip_gpio_debug_axi_ctrl_user_02_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_gpio_debug_axi_ctrl_user_02_0 || ORIG_REF_NAME==ulp_ip_gpio_debug_axi_ctrl_user_02_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_user_03_0/ulp_ip_gpio_debug_axi_ctrl_user_03_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_gpio_debug_axi_ctrl_user_03_0 || ORIG_REF_NAME==ulp_ip_gpio_debug_axi_ctrl_user_03_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_user_debug_00_0/ulp_ip_gpio_debug_axi_ctrl_user_debug_00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_gpio_debug_axi_ctrl_user_debug_00_0 || ORIG_REF_NAME==ulp_ip_gpio_debug_axi_ctrl_user_debug_00_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_inv_aresetn_ctrl_00_0/ulp_ip_inv_aresetn_ctrl_00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_inv_aresetn_ctrl_00_0 || ORIG_REF_NAME==ulp_ip_inv_aresetn_ctrl_00_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ict_axi_data_h2c_01_0/ulp_ict_axi_data_h2c_01_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ict_axi_data_h2c_01_0 || ORIG_REF_NAME==ulp_ict_axi_data_h2c_01_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_gpio_debug_axi_data_h2c_01_0/ulp_ip_gpio_debug_axi_data_h2c_01_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_gpio_debug_axi_data_h2c_01_0 || ORIG_REF_NAME==ulp_ip_gpio_debug_axi_data_h2c_01_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_psr_aresetn_ctrl_slr0_0/ulp_ip_psr_aresetn_ctrl_slr0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_psr_aresetn_ctrl_slr0_0 || ORIG_REF_NAME==ulp_ip_psr_aresetn_ctrl_slr0_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_psr_aresetn_ctrl_slr1_0/ulp_ip_psr_aresetn_ctrl_slr1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_psr_aresetn_ctrl_slr1_0 || ORIG_REF_NAME==ulp_ip_psr_aresetn_ctrl_slr1_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_psr_aresetn_ctrl_slr2_0/ulp_ip_psr_aresetn_ctrl_slr2_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_psr_aresetn_ctrl_slr2_0 || ORIG_REF_NAME==ulp_ip_psr_aresetn_ctrl_slr2_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_psr_aresetn_ctrl_slr3_0/ulp_ip_psr_aresetn_ctrl_slr3_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_psr_aresetn_ctrl_slr3_0 || ORIG_REF_NAME==ulp_ip_psr_aresetn_ctrl_slr3_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_psr_aresetn_kernel_00_slr0_0/ulp_ip_psr_aresetn_kernel_00_slr0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_psr_aresetn_kernel_00_slr0_0 || ORIG_REF_NAME==ulp_ip_psr_aresetn_kernel_00_slr0_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_psr_aresetn_kernel_00_slr1_0/ulp_ip_psr_aresetn_kernel_00_slr1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_psr_aresetn_kernel_00_slr1_0 || ORIG_REF_NAME==ulp_ip_psr_aresetn_kernel_00_slr1_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_psr_aresetn_kernel_00_slr2_0/ulp_ip_psr_aresetn_kernel_00_slr2_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_psr_aresetn_kernel_00_slr2_0 || ORIG_REF_NAME==ulp_ip_psr_aresetn_kernel_00_slr2_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_psr_aresetn_kernel_00_slr3_0/ulp_ip_psr_aresetn_kernel_00_slr3_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_psr_aresetn_kernel_00_slr3_0 || ORIG_REF_NAME==ulp_ip_psr_aresetn_kernel_00_slr3_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_psr_aresetn_kernel_01_slr0_0/ulp_ip_psr_aresetn_kernel_01_slr0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_psr_aresetn_kernel_01_slr0_0 || ORIG_REF_NAME==ulp_ip_psr_aresetn_kernel_01_slr0_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_psr_aresetn_kernel_01_slr1_0/ulp_ip_psr_aresetn_kernel_01_slr1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_psr_aresetn_kernel_01_slr1_0 || ORIG_REF_NAME==ulp_ip_psr_aresetn_kernel_01_slr1_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_psr_aresetn_kernel_01_slr2_0/ulp_ip_psr_aresetn_kernel_01_slr2_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_psr_aresetn_kernel_01_slr2_0 || ORIG_REF_NAME==ulp_ip_psr_aresetn_kernel_01_slr2_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_psr_aresetn_kernel_01_slr3_0/ulp_ip_psr_aresetn_kernel_01_slr3_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_psr_aresetn_kernel_01_slr3_0 || ORIG_REF_NAME==ulp_ip_psr_aresetn_kernel_01_slr3_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_psr_aresetn_pcie_slr0_0/ulp_ip_psr_aresetn_pcie_slr0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_psr_aresetn_pcie_slr0_0 || ORIG_REF_NAME==ulp_ip_psr_aresetn_pcie_slr0_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_psr_aresetn_pcie_slr1_0/ulp_ip_psr_aresetn_pcie_slr1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_psr_aresetn_pcie_slr1_0 || ORIG_REF_NAME==ulp_ip_psr_aresetn_pcie_slr1_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_psr_aresetn_pcie_slr2_0/ulp_ip_psr_aresetn_pcie_slr2_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_psr_aresetn_pcie_slr2_0 || ORIG_REF_NAME==ulp_ip_psr_aresetn_pcie_slr2_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_psr_aresetn_pcie_slr3_0/ulp_ip_psr_aresetn_pcie_slr3_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_psr_aresetn_pcie_slr3_0 || ORIG_REF_NAME==ulp_ip_psr_aresetn_pcie_slr3_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_psr_aresetn_freerun_slr0_0/ulp_ip_psr_aresetn_freerun_slr0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_psr_aresetn_freerun_slr0_0 || ORIG_REF_NAME==ulp_ip_psr_aresetn_freerun_slr0_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_psr_aresetn_freerun_slr1_0/ulp_ip_psr_aresetn_freerun_slr1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_psr_aresetn_freerun_slr1_0 || ORIG_REF_NAME==ulp_ip_psr_aresetn_freerun_slr1_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_psr_aresetn_freerun_slr2_0/ulp_ip_psr_aresetn_freerun_slr2_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_psr_aresetn_freerun_slr2_0 || ORIG_REF_NAME==ulp_ip_psr_aresetn_freerun_slr2_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ip_psr_aresetn_freerun_slr3_0/ulp_ip_psr_aresetn_freerun_slr3_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ip_psr_aresetn_freerun_slr3_0 || ORIG_REF_NAME==ulp_ip_psr_aresetn_freerun_slr3_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_satellite_gpio_slice_1_0/ulp_satellite_gpio_slice_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_satellite_gpio_slice_1_0 || ORIG_REF_NAME==ulp_satellite_gpio_slice_1_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_xbar_2/ulp_xbar_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_xbar_2 || ORIG_REF_NAME==ulp_xbar_2} -quiet] -quiet

# IP: bd/ulp/ip/ulp_xbar_3/ulp_xbar_3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_xbar_3 || ORIG_REF_NAME==ulp_xbar_3} -quiet] -quiet

# IP: bd/ulp/ip/ulp_xbar_4/ulp_xbar_4.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_xbar_4 || ORIG_REF_NAME==ulp_xbar_4} -quiet] -quiet

# IP: bd/ulp/ip/ulp_topKQueryScores_1_0/ulp_topKQueryScores_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_topKQueryScores_1_0 || ORIG_REF_NAME==ulp_topKQueryScores_1_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ii_level1_wire_ulp_s_irq_kernel_00_1_interrupt_concat_0/ulp_ii_level1_wire_ulp_s_irq_kernel_00_1_interrupt_concat_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ii_level1_wire_ulp_s_irq_kernel_00_1_interrupt_concat_0 || ORIG_REF_NAME==ulp_ii_level1_wire_ulp_s_irq_kernel_00_1_interrupt_concat_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ii_level1_wire_ulp_s_irq_kernel_00_1_interrupt_concat_0_0/ulp_ii_level1_wire_ulp_s_irq_kernel_00_1_interrupt_concat_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ii_level1_wire_ulp_s_irq_kernel_00_1_interrupt_concat_0_0 || ORIG_REF_NAME==ulp_ii_level1_wire_ulp_s_irq_kernel_00_1_interrupt_concat_0_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ii_level1_wire_ulp_s_irq_kernel_00_1_interrupt_concat_1_0/ulp_ii_level1_wire_ulp_s_irq_kernel_00_1_interrupt_concat_1_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ii_level1_wire_ulp_s_irq_kernel_00_1_interrupt_concat_1_0 || ORIG_REF_NAME==ulp_ii_level1_wire_ulp_s_irq_kernel_00_1_interrupt_concat_1_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ii_level1_wire_ulp_s_irq_kernel_00_1_interrupt_concat_2_0/ulp_ii_level1_wire_ulp_s_irq_kernel_00_1_interrupt_concat_2_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ii_level1_wire_ulp_s_irq_kernel_00_1_interrupt_concat_2_0 || ORIG_REF_NAME==ulp_ii_level1_wire_ulp_s_irq_kernel_00_1_interrupt_concat_2_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_ii_level1_wire_ulp_s_irq_kernel_00_1_interrupt_concat_3_0/ulp_ii_level1_wire_ulp_s_irq_kernel_00_1_interrupt_concat_3_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_ii_level1_wire_ulp_s_irq_kernel_00_1_interrupt_concat_3_0 || ORIG_REF_NAME==ulp_ii_level1_wire_ulp_s_irq_kernel_00_1_interrupt_concat_3_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_irq_const_tieoff_0/ulp_irq_const_tieoff_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_irq_const_tieoff_0 || ORIG_REF_NAME==ulp_irq_const_tieoff_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_s00_regslice_38/ulp_s00_regslice_38.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_s00_regslice_38 || ORIG_REF_NAME==ulp_s00_regslice_38} -quiet] -quiet

# IP: bd/ulp/ip/ulp_s00_regslice_39/ulp_s00_regslice_39.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_s00_regslice_39 || ORIG_REF_NAME==ulp_s00_regslice_39} -quiet] -quiet

# IP: bd/ulp/ip/ulp_m00_regslice_2/ulp_m00_regslice_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_m00_regslice_2 || ORIG_REF_NAME==ulp_m00_regslice_2} -quiet] -quiet

# IP: bd/ulp/ip/ulp_m01_regslice_2/ulp_m01_regslice_2.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_m01_regslice_2 || ORIG_REF_NAME==ulp_m01_regslice_2} -quiet] -quiet

# IP: bd/ulp/ip/ulp_m02_regslice_0/ulp_m02_regslice_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_m02_regslice_0 || ORIG_REF_NAME==ulp_m02_regslice_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_m03_regslice_0/ulp_m03_regslice_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_m03_regslice_0 || ORIG_REF_NAME==ulp_m03_regslice_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_s00_regslice_40/ulp_s00_regslice_40.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_s00_regslice_40 || ORIG_REF_NAME==ulp_s00_regslice_40} -quiet] -quiet

# IP: bd/ulp/ip/ulp_s00_regslice_41/ulp_s00_regslice_41.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_s00_regslice_41 || ORIG_REF_NAME==ulp_s00_regslice_41} -quiet] -quiet

# IP: bd/ulp/ip/ulp_m00_regslice_3/ulp_m00_regslice_3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_m00_regslice_3 || ORIG_REF_NAME==ulp_m00_regslice_3} -quiet] -quiet

# IP: bd/ulp/ip/ulp_m01_regslice_3/ulp_m01_regslice_3.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_m01_regslice_3 || ORIG_REF_NAME==ulp_m01_regslice_3} -quiet] -quiet

# IP: bd/ulp/ip/ulp_auto_cc_0/ulp_auto_cc_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_auto_cc_0 || ORIG_REF_NAME==ulp_auto_cc_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_s00_regslice_42/ulp_s00_regslice_42.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_s00_regslice_42 || ORIG_REF_NAME==ulp_s00_regslice_42} -quiet] -quiet

# IP: bd/ulp/ip/ulp_s00_regslice_43/ulp_s00_regslice_43.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_s00_regslice_43 || ORIG_REF_NAME==ulp_s00_regslice_43} -quiet] -quiet

# IP: bd/ulp/ip/ulp_s00_regslice_44/ulp_s00_regslice_44.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_s00_regslice_44 || ORIG_REF_NAME==ulp_s00_regslice_44} -quiet] -quiet

# IP: bd/ulp/ip/ulp_s00_regslice_45/ulp_s00_regslice_45.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_s00_regslice_45 || ORIG_REF_NAME==ulp_s00_regslice_45} -quiet] -quiet

# IP: bd/ulp/ip/ulp_auto_ds_0/ulp_auto_ds_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_auto_ds_0 || ORIG_REF_NAME==ulp_auto_ds_0} -quiet] -quiet

# IP: bd/ulp/ip/ulp_auto_pc_0/ulp_auto_pc_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ulp_auto_pc_0 || ORIG_REF_NAME==ulp_auto_pc_0} -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ulp_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp'. Do not add the DONT_TOUCH constraint.

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/output/ulp_ooc_copy.xdc
