# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.runs/my_rm_synth_1/ulp.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "my_rm_synth_1" START { ROLLUP_AUTO }
set_param project.enablePRFlowIPI 1
set_param bd.debug_profile.script /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/.local/debug_profile_automation.tcl
set_param route.sllAssign.enableILPBasedSllAssignment 0
set_param bd.enable_dpa 1
set_param project.loadTopLevelOOCConstrs 1
set_param project.gatelevelSubdesign 1
set_param place.ultrathreadsUsed 0
set_param ips.enableSLRParameter 2
set_param hd.Visual 0
set_param general.maxThreads 1
set_param bd.ForceAppCoreUpgrade 1
set_param compiler.enablePerformanceTrace 1
set_param bd.skipSupportedIPCheck 1
set_param project.vivado.isBlockSynthRun true
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xcu250-figd2104-2L-e
set_property tool_flow SDx [current_project]

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.cache/wt [current_project]
set_property parent.project_path /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {/home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/.local/hw_platform/board} [current_project]
set_property board_part xilinx.com:au250:part0:1.4 [current_project]
set_property ip_repo_paths {
  /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/int/xo/ip_repo/xilinx_com_hls_topKQueryScores_1_0
  /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/.local/hw_platform/iprepo
  /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/.local/hw_platform/ipcache
  /tools/Xilinx/Vitis/2022.2/data/ip
} [current_project]
update_ip_catalog
set_property ip_output_repo /home/nmath018/topK_feature/hls_catch22/.ipcache [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.srcs/my_rm/bd/ulp/ulp.bd
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_7/bd_1860_s_ip_axi_ctrl_mgmt_00_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_8/bd_1860_m_ip_axi_ctrl_mgmt_00_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_9/bd_1860_s_ip_axi_ctrl_mgmt_01_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_10/bd_1860_m_ip_axi_ctrl_mgmt_01_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_11/bd_1860_s_ip_axi_ctrl_user_00_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_12/bd_1860_m_ip_axi_ctrl_user_00_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_13/bd_1860_s_ip_axi_ctrl_user_01_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_14/bd_1860_m_ip_axi_ctrl_user_01_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_15/bd_1860_s_ip_axi_ctrl_user_02_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_16/bd_1860_m_ip_axi_ctrl_user_02_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_17/bd_1860_s_ip_axi_ctrl_user_03_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_18/bd_1860_m_ip_axi_ctrl_user_03_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_19/bd_1860_s_ip_axi_ctrl_user_debug_00_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_20/bd_1860_m_ip_axi_ctrl_user_debug_00_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_21/bd_1860_s_ip_axi_data_c2h_00_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_22/bd_1860_m_ip_axi_data_c2h_00_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_23/bd_1860_s_ip_axi_data_h2c_00_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_24/bd_1860_m_ip_axi_data_h2c_00_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_25/bd_1860_s_ip_axi_data_h2c_01_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_26/bd_1860_m_ip_axi_data_h2c_01_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_27/bd_1860_s_ip_axi_data_h2c_02_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_28/bd_1860_m_ip_axi_data_h2c_02_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_29/bd_1860_s_ip_axi_data_h2c_03_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_30/bd_1860_m_ip_axi_data_h2c_03_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_31/bd_1860_s_ip_axi_data_u2s_00_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_32/bd_1860_m_ip_axi_data_u2s_00_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/bd_1860_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/src/ii_level1_wire_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/uuid_stamp.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_0/ip/ip_5/bd_b35e_psr_aclk1_SLR1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_0/ip/ip_5/bd_b35e_psr_aclk1_SLR1_0.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_0/ip/ip_5/bd_b35e_psr_aclk1_SLR1_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_0/ip/ip_5/bd_b35e_psr_aclk1_SLR1_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_0/ip/ip_5/bd_b35e_psr_aclk1_SLR1_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_0/ip/ip_13/bd_b35e_psr_aclk3_SLR1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_0/ip/ip_13/bd_b35e_psr_aclk3_SLR1_0.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_0/ip/ip_13/bd_b35e_psr_aclk3_SLR1_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_0/ip/ip_13/bd_b35e_psr_aclk3_SLR1_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_0/ip/ip_13/bd_b35e_psr_aclk3_SLR1_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_1/ip/ip_1/bd_928c_psr0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_1/ip/ip_1/bd_928c_psr0_0.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_1/ip/ip_2/bd_928c_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_1/ip/ip_2/bd_928c_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_1/ip/ip_3/bd_928c_psr_aclk1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_1/ip/ip_3/bd_928c_psr_aclk1_0.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_1/ip/ip_4/bd_928c_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_1/ip/ip_5/bd_928c_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_1/ip/ip_6/bd_928c_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_1/ip/ip_7/bd_928c_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_1/ip/ip_8/bd_928c_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_1/ip/ip_12/bd_928c_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_1/ip/ip_13/bd_928c_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_1/ip/ip_14/bd_928c_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_1/ip/ip_15/bd_928c_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_1/ip/ip_16/bd_928c_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_1/ip/ip_17/bd_928c_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_1/ip/ip_21/bd_928c_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_1/ip/ip_22/bd_928c_sarn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_1/ip/ip_23/bd_928c_srn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_1/ip/ip_24/bd_928c_sawn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_1/ip/ip_25/bd_928c_swn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_1/ip/ip_26/bd_928c_sbn_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_1/ip/ip_27/bd_928c_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_1/ip/ip_28/bd_928c_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_1/ip/ip_29/bd_928c_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_1/ip/ip_30/bd_928c_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_1/ip/ip_31/bd_928c_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_1/ip/ip_32/bd_928c_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_0/ip/ip_17/ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_0/ip/ip_20/bd_b35e_vip_S01_AXI_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_0/ip/ip_21/bd_b35e_vip_S04_AXI_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_0/ip/ip_22/bd_b35e_vip_M00_AXI_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_0/ip/ip_23/bd_b35e_rs_M00_AXI_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_0/ip/ip_23/bd_b35e_rs_M00_AXI_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_0/ip/ip_19/bd_b35e_interconnect_ddrmem_ctrl_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_0/ip/ip_16/bd_b35e_psr_ctrl_interconnect_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_0/ip/ip_16/bd_b35e_psr_ctrl_interconnect_0.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_0/ip/ip_16/bd_b35e_psr_ctrl_interconnect_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_0/bd_b35e_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/ulp_memory_subsystem_0.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/ulp_memory_subsystem_0.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_1/bd_1361_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_2/bd_1361_build_info_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_3/bd_1361_gapping_demand_toggle_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_6/bd_1361_gpio_gapping_demand_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_6/bd_1361_gpio_gapping_demand_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_6/bd_1361_gpio_gapping_demand_0.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_11/bd_1361_clock_throttling_avg_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_14/bd_1361_gpio_ucs_control_status_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_14/bd_1361_gpio_ucs_control_status_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_14/bd_1361_gpio_ucs_control_status_0.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_17/bd_1361_clock_shutdown_latch_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_58/bd_1361_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_59/bd_1361_frequency_counter_aclk_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_60/bd_1361_frequency_counter_aclk_kernel_00_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_61/bd_1361_frequency_counter_aclk_kernel_01_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_62/bd_1361_psreset_aclk_freerun_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_62/bd_1361_psreset_aclk_freerun_0.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_62/bd_1361_psreset_aclk_freerun_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_65/bd_1361_clkwiz_aclk_kernel_00_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_65/bd_1361_clkwiz_aclk_kernel_00_0.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_65/bd_1361_clkwiz_aclk_kernel_00_0_late.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_65/bd_1361_clkwiz_aclk_kernel_00_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_66/bd_1361_clock_throttling_aclk_kernel_00_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_66/bd_1361_clock_throttling_aclk_kernel_00_0.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_86/bd_1361_psreset_kernel_00_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_86/bd_1361_psreset_kernel_00_0.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_86/bd_1361_psreset_kernel_00_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_89/bd_1361_clkwiz_aclk_kernel_01_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_89/bd_1361_clkwiz_aclk_kernel_01_0.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_89/bd_1361_clkwiz_aclk_kernel_01_0_late.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_89/bd_1361_clkwiz_aclk_kernel_01_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_90/bd_1361_clock_throttling_aclk_kernel_01_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_90/bd_1361_clock_throttling_aclk_kernel_01_0.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_110/bd_1361_psreset_kernel_01_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_110/bd_1361_psreset_kernel_01_0.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_110/bd_1361_psreset_kernel_01_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_111/bd_1361_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_111/bd_1361_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/ip/ip_111/bd_1361_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/bd_0/bd_1361_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/ulp_ss_ucs_0.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ss_ucs_0/synth/ulp_ss_ucs_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_cc_axi_data_h2c_00_0/ulp_ip_cc_axi_data_h2c_00_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_cc_axi_data_h2c_00_0/ulp_ip_cc_axi_data_h2c_00_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_cc_axi_data_h2c_00_0/ulp_ip_cc_axi_data_h2c_00_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_cc_axi_data_h2c_00_0/ulp_ip_cc_axi_data_h2c_00_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_cc_axi_data_h2c_00_0/ulp_ip_cc_axi_data_h2c_00_0_slr.xdc]
set_property used_in_synthesis false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_cc_axi_data_h2c_01_0/ulp_ip_cc_axi_data_h2c_01_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_cc_axi_data_h2c_01_0/ulp_ip_cc_axi_data_h2c_01_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_cc_axi_data_h2c_01_0/ulp_ip_cc_axi_data_h2c_01_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_cc_axi_data_h2c_01_0/ulp_ip_cc_axi_data_h2c_01_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_cc_axi_data_h2c_01_0/ulp_ip_cc_axi_data_h2c_01_0_slr.xdc]
set_property used_in_synthesis false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_cc_axi_data_h2c_02_0/ulp_ip_cc_axi_data_h2c_02_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_cc_axi_data_h2c_02_0/ulp_ip_cc_axi_data_h2c_02_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_cc_axi_data_h2c_02_0/ulp_ip_cc_axi_data_h2c_02_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_cc_axi_data_h2c_02_0/ulp_ip_cc_axi_data_h2c_02_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_cc_axi_data_h2c_02_0/ulp_ip_cc_axi_data_h2c_02_0_slr.xdc]
set_property used_in_synthesis false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_cc_axi_data_h2c_03_0/ulp_ip_cc_axi_data_h2c_03_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_cc_axi_data_h2c_03_0/ulp_ip_cc_axi_data_h2c_03_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_cc_axi_data_h2c_03_0/ulp_ip_cc_axi_data_h2c_03_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_cc_axi_data_h2c_03_0/ulp_ip_cc_axi_data_h2c_03_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_cc_axi_data_h2c_03_0/ulp_ip_cc_axi_data_h2c_03_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_rs_axi_data_h2c_03_0/ulp_ip_rs_axi_data_h2c_03_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_rs_axi_data_h2c_03_0/ulp_ip_rs_axi_data_h2c_03_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_rs_axi_ctrl_user_03_0/ulp_ip_rs_axi_ctrl_user_03_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_rs_axi_ctrl_user_03_0/ulp_ip_rs_axi_ctrl_user_03_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_rs_axi_data_c2h_00_0/ulp_ip_rs_axi_data_c2h_00_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_rs_axi_data_c2h_00_0/ulp_ip_rs_axi_data_c2h_00_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_shell_cmp_subsystem_0_0/bd_0/ip/ip_0/bd_3f43_build_info_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_shell_cmp_subsystem_0_0/bd_1/ip/ip_0/constraints/axi_jtag.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_shell_cmp_subsystem_0_0/bd_1/ip/ip_0/bd_53f9_axi_jtag_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_shell_cmp_subsystem_0_0/bd_1/ip/ip_1/constraints/bsip.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_shell_cmp_subsystem_0_0/bd_1/ip/ip_1/bd_53f9_bsip_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_shell_cmp_subsystem_0_0/bd_1/ip/ip_2/constraints/bs_switch.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_shell_cmp_subsystem_0_0/bd_1/ip/ip_2/bd_53f9_bs_switch_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_shell_cmp_subsystem_0_0/bd_1/bd_53f9_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_shell_cmp_subsystem_0_0/bd_0/ip/ip_2/bd_3f43_user_debug_bridge_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_shell_cmp_subsystem_0_0/bd_2/ip/ip_0/constraints/xsdbm_cc_early.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_shell_cmp_subsystem_0_0/bd_2/ip/ip_0/constraints/xsdbm_cc_late.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_shell_cmp_subsystem_0_0/bd_2/ip/ip_0/constraints/xsdbm_gc_late.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_shell_cmp_subsystem_0_0/bd_2/ip/ip_0/bd_7b93_xsdbm_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_shell_cmp_subsystem_0_0/bd_2/bd_7b93_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_shell_cmp_subsystem_0_0/bd_0/ip/ip_3/bd_3f43_user_debug_hub_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_shell_cmp_subsystem_0_0/bd_0/bd_3f43_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_shell_cmp_subsystem_0_0/synth/ulp_shell_cmp_subsystem_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_shell_cmp_subsystem_0_0/ulp_shell_cmp_subsystem_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_mgmt_00_0/ulp_ip_gpio_debug_axi_ctrl_mgmt_00_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_mgmt_00_0/ulp_ip_gpio_debug_axi_ctrl_mgmt_00_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_mgmt_00_0/ulp_ip_gpio_debug_axi_ctrl_mgmt_00_0.xdc]
set_property used_in_synthesis false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_mgmt_00_0/ulp_ip_gpio_debug_axi_ctrl_mgmt_00_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_mgmt_00_0/ulp_ip_gpio_debug_axi_ctrl_mgmt_00_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_mgmt_01_0/ulp_ip_gpio_debug_axi_ctrl_mgmt_01_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_mgmt_01_0/ulp_ip_gpio_debug_axi_ctrl_mgmt_01_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_mgmt_01_0/ulp_ip_gpio_debug_axi_ctrl_mgmt_01_0.xdc]
set_property used_in_synthesis false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_mgmt_01_0/ulp_ip_gpio_debug_axi_ctrl_mgmt_01_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_mgmt_01_0/ulp_ip_gpio_debug_axi_ctrl_mgmt_01_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_user_00_0/ulp_ip_gpio_debug_axi_ctrl_user_00_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_user_00_0/ulp_ip_gpio_debug_axi_ctrl_user_00_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_user_00_0/ulp_ip_gpio_debug_axi_ctrl_user_00_0.xdc]
set_property used_in_synthesis false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_user_00_0/ulp_ip_gpio_debug_axi_ctrl_user_00_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_user_00_0/ulp_ip_gpio_debug_axi_ctrl_user_00_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_user_01_0/ulp_ip_gpio_debug_axi_ctrl_user_01_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_user_01_0/ulp_ip_gpio_debug_axi_ctrl_user_01_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_user_01_0/ulp_ip_gpio_debug_axi_ctrl_user_01_0.xdc]
set_property used_in_synthesis false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_user_01_0/ulp_ip_gpio_debug_axi_ctrl_user_01_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_user_01_0/ulp_ip_gpio_debug_axi_ctrl_user_01_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_user_02_0/ulp_ip_gpio_debug_axi_ctrl_user_02_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_user_02_0/ulp_ip_gpio_debug_axi_ctrl_user_02_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_user_02_0/ulp_ip_gpio_debug_axi_ctrl_user_02_0.xdc]
set_property used_in_synthesis false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_user_02_0/ulp_ip_gpio_debug_axi_ctrl_user_02_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_user_02_0/ulp_ip_gpio_debug_axi_ctrl_user_02_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_user_03_0/ulp_ip_gpio_debug_axi_ctrl_user_03_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_user_03_0/ulp_ip_gpio_debug_axi_ctrl_user_03_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_user_03_0/ulp_ip_gpio_debug_axi_ctrl_user_03_0.xdc]
set_property used_in_synthesis false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_user_03_0/ulp_ip_gpio_debug_axi_ctrl_user_03_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_user_03_0/ulp_ip_gpio_debug_axi_ctrl_user_03_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_user_debug_00_0/ulp_ip_gpio_debug_axi_ctrl_user_debug_00_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_user_debug_00_0/ulp_ip_gpio_debug_axi_ctrl_user_debug_00_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_gpio_debug_axi_ctrl_user_debug_00_0/ulp_ip_gpio_debug_axi_ctrl_user_debug_00_0.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_gpio_debug_axi_data_h2c_01_0/ulp_ip_gpio_debug_axi_data_h2c_01_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_gpio_debug_axi_data_h2c_01_0/ulp_ip_gpio_debug_axi_data_h2c_01_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_gpio_debug_axi_data_h2c_01_0/ulp_ip_gpio_debug_axi_data_h2c_01_0.xdc]
set_property used_in_synthesis false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_gpio_debug_axi_data_h2c_01_0/ulp_ip_gpio_debug_axi_data_h2c_01_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_gpio_debug_axi_data_h2c_01_0/ulp_ip_gpio_debug_axi_data_h2c_01_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_ctrl_slr0_0/ulp_ip_psr_aresetn_ctrl_slr0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_ctrl_slr0_0/ulp_ip_psr_aresetn_ctrl_slr0_0.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_ctrl_slr0_0/ulp_ip_psr_aresetn_ctrl_slr0_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_ctrl_slr0_0/ulp_ip_psr_aresetn_ctrl_slr0_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_ctrl_slr0_0/ulp_ip_psr_aresetn_ctrl_slr0_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_ctrl_slr1_0/ulp_ip_psr_aresetn_ctrl_slr1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_ctrl_slr1_0/ulp_ip_psr_aresetn_ctrl_slr1_0.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_ctrl_slr1_0/ulp_ip_psr_aresetn_ctrl_slr1_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_ctrl_slr1_0/ulp_ip_psr_aresetn_ctrl_slr1_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_ctrl_slr1_0/ulp_ip_psr_aresetn_ctrl_slr1_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_ctrl_slr2_0/ulp_ip_psr_aresetn_ctrl_slr2_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_ctrl_slr2_0/ulp_ip_psr_aresetn_ctrl_slr2_0.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_ctrl_slr2_0/ulp_ip_psr_aresetn_ctrl_slr2_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_ctrl_slr2_0/ulp_ip_psr_aresetn_ctrl_slr2_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_ctrl_slr2_0/ulp_ip_psr_aresetn_ctrl_slr2_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_ctrl_slr3_0/ulp_ip_psr_aresetn_ctrl_slr3_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_ctrl_slr3_0/ulp_ip_psr_aresetn_ctrl_slr3_0.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_ctrl_slr3_0/ulp_ip_psr_aresetn_ctrl_slr3_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_ctrl_slr3_0/ulp_ip_psr_aresetn_ctrl_slr3_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_ctrl_slr3_0/ulp_ip_psr_aresetn_ctrl_slr3_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_00_slr0_0/ulp_ip_psr_aresetn_kernel_00_slr0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_00_slr0_0/ulp_ip_psr_aresetn_kernel_00_slr0_0.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_00_slr0_0/ulp_ip_psr_aresetn_kernel_00_slr0_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_00_slr0_0/ulp_ip_psr_aresetn_kernel_00_slr0_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_00_slr0_0/ulp_ip_psr_aresetn_kernel_00_slr0_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_00_slr1_0/ulp_ip_psr_aresetn_kernel_00_slr1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_00_slr1_0/ulp_ip_psr_aresetn_kernel_00_slr1_0.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_00_slr1_0/ulp_ip_psr_aresetn_kernel_00_slr1_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_00_slr1_0/ulp_ip_psr_aresetn_kernel_00_slr1_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_00_slr1_0/ulp_ip_psr_aresetn_kernel_00_slr1_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_00_slr2_0/ulp_ip_psr_aresetn_kernel_00_slr2_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_00_slr2_0/ulp_ip_psr_aresetn_kernel_00_slr2_0.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_00_slr2_0/ulp_ip_psr_aresetn_kernel_00_slr2_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_00_slr2_0/ulp_ip_psr_aresetn_kernel_00_slr2_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_00_slr2_0/ulp_ip_psr_aresetn_kernel_00_slr2_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_00_slr3_0/ulp_ip_psr_aresetn_kernel_00_slr3_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_00_slr3_0/ulp_ip_psr_aresetn_kernel_00_slr3_0.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_00_slr3_0/ulp_ip_psr_aresetn_kernel_00_slr3_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_00_slr3_0/ulp_ip_psr_aresetn_kernel_00_slr3_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_00_slr3_0/ulp_ip_psr_aresetn_kernel_00_slr3_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_01_slr0_0/ulp_ip_psr_aresetn_kernel_01_slr0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_01_slr0_0/ulp_ip_psr_aresetn_kernel_01_slr0_0.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_01_slr0_0/ulp_ip_psr_aresetn_kernel_01_slr0_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_01_slr0_0/ulp_ip_psr_aresetn_kernel_01_slr0_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_01_slr0_0/ulp_ip_psr_aresetn_kernel_01_slr0_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_01_slr1_0/ulp_ip_psr_aresetn_kernel_01_slr1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_01_slr1_0/ulp_ip_psr_aresetn_kernel_01_slr1_0.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_01_slr1_0/ulp_ip_psr_aresetn_kernel_01_slr1_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_01_slr1_0/ulp_ip_psr_aresetn_kernel_01_slr1_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_01_slr1_0/ulp_ip_psr_aresetn_kernel_01_slr1_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_01_slr2_0/ulp_ip_psr_aresetn_kernel_01_slr2_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_01_slr2_0/ulp_ip_psr_aresetn_kernel_01_slr2_0.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_01_slr2_0/ulp_ip_psr_aresetn_kernel_01_slr2_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_01_slr2_0/ulp_ip_psr_aresetn_kernel_01_slr2_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_01_slr2_0/ulp_ip_psr_aresetn_kernel_01_slr2_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_01_slr3_0/ulp_ip_psr_aresetn_kernel_01_slr3_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_01_slr3_0/ulp_ip_psr_aresetn_kernel_01_slr3_0.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_01_slr3_0/ulp_ip_psr_aresetn_kernel_01_slr3_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_01_slr3_0/ulp_ip_psr_aresetn_kernel_01_slr3_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_01_slr3_0/ulp_ip_psr_aresetn_kernel_01_slr3_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_pcie_slr0_0/ulp_ip_psr_aresetn_pcie_slr0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_pcie_slr0_0/ulp_ip_psr_aresetn_pcie_slr0_0.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_pcie_slr0_0/ulp_ip_psr_aresetn_pcie_slr0_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_pcie_slr0_0/ulp_ip_psr_aresetn_pcie_slr0_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_pcie_slr0_0/ulp_ip_psr_aresetn_pcie_slr0_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_pcie_slr1_0/ulp_ip_psr_aresetn_pcie_slr1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_pcie_slr1_0/ulp_ip_psr_aresetn_pcie_slr1_0.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_pcie_slr1_0/ulp_ip_psr_aresetn_pcie_slr1_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_pcie_slr1_0/ulp_ip_psr_aresetn_pcie_slr1_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_pcie_slr1_0/ulp_ip_psr_aresetn_pcie_slr1_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_pcie_slr2_0/ulp_ip_psr_aresetn_pcie_slr2_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_pcie_slr2_0/ulp_ip_psr_aresetn_pcie_slr2_0.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_pcie_slr2_0/ulp_ip_psr_aresetn_pcie_slr2_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_pcie_slr2_0/ulp_ip_psr_aresetn_pcie_slr2_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_pcie_slr2_0/ulp_ip_psr_aresetn_pcie_slr2_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_pcie_slr3_0/ulp_ip_psr_aresetn_pcie_slr3_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_pcie_slr3_0/ulp_ip_psr_aresetn_pcie_slr3_0.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_pcie_slr3_0/ulp_ip_psr_aresetn_pcie_slr3_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_pcie_slr3_0/ulp_ip_psr_aresetn_pcie_slr3_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_pcie_slr3_0/ulp_ip_psr_aresetn_pcie_slr3_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_freerun_slr0_0/ulp_ip_psr_aresetn_freerun_slr0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_freerun_slr0_0/ulp_ip_psr_aresetn_freerun_slr0_0.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_freerun_slr0_0/ulp_ip_psr_aresetn_freerun_slr0_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_freerun_slr0_0/ulp_ip_psr_aresetn_freerun_slr0_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_freerun_slr0_0/ulp_ip_psr_aresetn_freerun_slr0_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_freerun_slr1_0/ulp_ip_psr_aresetn_freerun_slr1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_freerun_slr1_0/ulp_ip_psr_aresetn_freerun_slr1_0.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_freerun_slr1_0/ulp_ip_psr_aresetn_freerun_slr1_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_freerun_slr1_0/ulp_ip_psr_aresetn_freerun_slr1_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_freerun_slr1_0/ulp_ip_psr_aresetn_freerun_slr1_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_freerun_slr2_0/ulp_ip_psr_aresetn_freerun_slr2_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_freerun_slr2_0/ulp_ip_psr_aresetn_freerun_slr2_0.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_freerun_slr2_0/ulp_ip_psr_aresetn_freerun_slr2_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_freerun_slr2_0/ulp_ip_psr_aresetn_freerun_slr2_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_freerun_slr2_0/ulp_ip_psr_aresetn_freerun_slr2_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_freerun_slr3_0/ulp_ip_psr_aresetn_freerun_slr3_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_freerun_slr3_0/ulp_ip_psr_aresetn_freerun_slr3_0.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_freerun_slr3_0/ulp_ip_psr_aresetn_freerun_slr3_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_freerun_slr3_0/ulp_ip_psr_aresetn_freerun_slr3_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_freerun_slr3_0/ulp_ip_psr_aresetn_freerun_slr3_0_slr.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_xbar_2/ulp_xbar_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_xbar_3/ulp_xbar_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_xbar_4/ulp_xbar_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_topKQueryScores_1_0/constraints/topKQueryScores_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_s00_regslice_38/ulp_s00_regslice_38_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_s00_regslice_38/ulp_s00_regslice_38_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_s00_regslice_39/ulp_s00_regslice_39_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_s00_regslice_39/ulp_s00_regslice_39_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_m00_regslice_2/ulp_m00_regslice_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_m00_regslice_2/ulp_m00_regslice_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_m01_regslice_2/ulp_m01_regslice_2_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_m01_regslice_2/ulp_m01_regslice_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_m02_regslice_0/ulp_m02_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_m02_regslice_0/ulp_m02_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_m03_regslice_0/ulp_m03_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_m03_regslice_0/ulp_m03_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_s00_regslice_40/ulp_s00_regslice_40_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_s00_regslice_40/ulp_s00_regslice_40_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_s00_regslice_41/ulp_s00_regslice_41_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_s00_regslice_41/ulp_s00_regslice_41_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_m00_regslice_3/ulp_m00_regslice_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_m00_regslice_3/ulp_m00_regslice_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_m01_regslice_3/ulp_m01_regslice_3_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_m01_regslice_3/ulp_m01_regslice_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_auto_cc_0/ulp_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_auto_cc_0/ulp_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_auto_cc_0/ulp_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_s00_regslice_42/ulp_s00_regslice_42_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_s00_regslice_42/ulp_s00_regslice_42_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_s00_regslice_43/ulp_s00_regslice_43_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_s00_regslice_43/ulp_s00_regslice_43_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_s00_regslice_44/ulp_s00_regslice_44_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_s00_regslice_44/ulp_s00_regslice_44_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_s00_regslice_45/ulp_s00_regslice_45_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_s00_regslice_45/ulp_s00_regslice_45_ooc.xdc]
set_property used_in_synthesis false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_auto_ds_0/ulp_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_auto_ds_0/ulp_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_auto_ds_0/ulp_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_auto_pc_0/ulp_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ulp_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc -mode out_of_context /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/output/ulp_ooc_copy.xdc
set_property used_in_implementation false [get_files /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/output/ulp_ooc_copy.xdc]
set_property processing_order LATE [get_files /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/output/ulp_ooc_copy.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top ulp -part xcu250-figd2104-2L-e -incremental_mode off -mode out_of_context
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}

rename_ref -prefix_all ulp_

OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ulp.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
OPTRACE "synth reports" END { }

if { [catch {
  file copy -force /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.runs/my_rm_synth_1/ulp.dcp /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ulp.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 status "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ulp_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ulp_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ulp_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ulp_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.ip_user_files/bd/ulp]} {
  catch { 
    file copy -force /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ulp_stub.v /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.ip_user_files/bd/ulp
  }
}

if {[file isdir /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.ip_user_files/bd/ulp]} {
  catch { 
    file copy -force /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ulp_stub.vhdl /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.ip_user_files/bd/ulp
  }
}
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "my_rm_synth_1" END { }
