// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="topKQueryScores_topKQueryScores,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcu250-figd2104-2L-e,HLS_INPUT_CLOCK=3.333000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.433090,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=1,HLS_SYN_DSP=0,HLS_SYN_FF=5275,HLS_SYN_LUT=7271,HLS_VERSION=2022_2}" *)

module topKQueryScores (
        ap_clk,
        ap_rst_n,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 84'd1;
parameter    ap_ST_fsm_state2 = 84'd2;
parameter    ap_ST_fsm_state3 = 84'd4;
parameter    ap_ST_fsm_state4 = 84'd8;
parameter    ap_ST_fsm_state5 = 84'd16;
parameter    ap_ST_fsm_state6 = 84'd32;
parameter    ap_ST_fsm_state7 = 84'd64;
parameter    ap_ST_fsm_state8 = 84'd128;
parameter    ap_ST_fsm_state9 = 84'd256;
parameter    ap_ST_fsm_state10 = 84'd512;
parameter    ap_ST_fsm_state11 = 84'd1024;
parameter    ap_ST_fsm_state12 = 84'd2048;
parameter    ap_ST_fsm_state13 = 84'd4096;
parameter    ap_ST_fsm_state14 = 84'd8192;
parameter    ap_ST_fsm_state15 = 84'd16384;
parameter    ap_ST_fsm_state16 = 84'd32768;
parameter    ap_ST_fsm_state17 = 84'd65536;
parameter    ap_ST_fsm_state18 = 84'd131072;
parameter    ap_ST_fsm_state19 = 84'd262144;
parameter    ap_ST_fsm_state20 = 84'd524288;
parameter    ap_ST_fsm_state21 = 84'd1048576;
parameter    ap_ST_fsm_state22 = 84'd2097152;
parameter    ap_ST_fsm_state23 = 84'd4194304;
parameter    ap_ST_fsm_state24 = 84'd8388608;
parameter    ap_ST_fsm_state25 = 84'd16777216;
parameter    ap_ST_fsm_state26 = 84'd33554432;
parameter    ap_ST_fsm_state27 = 84'd67108864;
parameter    ap_ST_fsm_state28 = 84'd134217728;
parameter    ap_ST_fsm_state29 = 84'd268435456;
parameter    ap_ST_fsm_state30 = 84'd536870912;
parameter    ap_ST_fsm_state31 = 84'd1073741824;
parameter    ap_ST_fsm_state32 = 84'd2147483648;
parameter    ap_ST_fsm_state33 = 84'd4294967296;
parameter    ap_ST_fsm_state34 = 84'd8589934592;
parameter    ap_ST_fsm_state35 = 84'd17179869184;
parameter    ap_ST_fsm_state36 = 84'd34359738368;
parameter    ap_ST_fsm_state37 = 84'd68719476736;
parameter    ap_ST_fsm_state38 = 84'd137438953472;
parameter    ap_ST_fsm_state39 = 84'd274877906944;
parameter    ap_ST_fsm_state40 = 84'd549755813888;
parameter    ap_ST_fsm_state41 = 84'd1099511627776;
parameter    ap_ST_fsm_state42 = 84'd2199023255552;
parameter    ap_ST_fsm_state43 = 84'd4398046511104;
parameter    ap_ST_fsm_state44 = 84'd8796093022208;
parameter    ap_ST_fsm_state45 = 84'd17592186044416;
parameter    ap_ST_fsm_state46 = 84'd35184372088832;
parameter    ap_ST_fsm_state47 = 84'd70368744177664;
parameter    ap_ST_fsm_state48 = 84'd140737488355328;
parameter    ap_ST_fsm_state49 = 84'd281474976710656;
parameter    ap_ST_fsm_state50 = 84'd562949953421312;
parameter    ap_ST_fsm_state51 = 84'd1125899906842624;
parameter    ap_ST_fsm_state52 = 84'd2251799813685248;
parameter    ap_ST_fsm_state53 = 84'd4503599627370496;
parameter    ap_ST_fsm_state54 = 84'd9007199254740992;
parameter    ap_ST_fsm_state55 = 84'd18014398509481984;
parameter    ap_ST_fsm_state56 = 84'd36028797018963968;
parameter    ap_ST_fsm_state57 = 84'd72057594037927936;
parameter    ap_ST_fsm_state58 = 84'd144115188075855872;
parameter    ap_ST_fsm_state59 = 84'd288230376151711744;
parameter    ap_ST_fsm_state60 = 84'd576460752303423488;
parameter    ap_ST_fsm_state61 = 84'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 84'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 84'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 84'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 84'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 84'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 84'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 84'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 84'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 84'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 84'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 84'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 84'd4722366482869645213696;
parameter    ap_ST_fsm_state74 = 84'd9444732965739290427392;
parameter    ap_ST_fsm_state75 = 84'd18889465931478580854784;
parameter    ap_ST_fsm_state76 = 84'd37778931862957161709568;
parameter    ap_ST_fsm_state77 = 84'd75557863725914323419136;
parameter    ap_ST_fsm_state78 = 84'd151115727451828646838272;
parameter    ap_ST_fsm_state79 = 84'd302231454903657293676544;
parameter    ap_ST_fsm_state80 = 84'd604462909807314587353088;
parameter    ap_ST_fsm_state81 = 84'd1208925819614629174706176;
parameter    ap_ST_fsm_state82 = 84'd2417851639229258349412352;
parameter    ap_ST_fsm_state83 = 84'd4835703278458516698824704;
parameter    ap_ST_fsm_state84 = 84'd9671406556917033397649408;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 64;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (64 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
wire    ap_continue;
reg    ap_done_reg;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [83:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] fs_matrix;
wire   [63:0] query_type;
wire   [31:0] k;
wire   [63:0] topK_indices;
reg    gmem_blk_n_AR;
wire    ap_CS_fsm_state2;
reg    gmem_blk_n_R;
wire    ap_CS_fsm_state72;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state73;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state74;
reg   [63:0] query_type_read_reg_329;
reg   [63:0] fs_matrix_read_reg_335;
wire   [2:0] trunc_ln19_fu_185_p1;
reg   [2:0] trunc_ln19_reg_340;
reg   [60:0] trunc_ln19_1_reg_346;
reg   [60:0] trunc_ln19_4_reg_357;
reg   [60:0] trunc_ln19_7_reg_362;
reg   [63:0] gmem_addr_read_reg_379;
reg   [63:0] gmem_addr_3_read_reg_384;
wire   [31:0] trunc_ln19_3_fu_281_p1;
reg   [31:0] trunc_ln19_3_reg_389;
reg   [63:0] gmem_addr_4_read_reg_394;
wire   [31:0] trunc_ln19_2_fu_301_p1;
reg   [31:0] trunc_ln19_2_reg_399;
wire    ap_CS_fsm_state75;
wire   [31:0] trunc_ln19_5_fu_310_p1;
reg   [31:0] trunc_ln19_5_reg_404;
wire   [63:0] grp_fu_176_p1;
reg   [63:0] conv_reg_409;
wire    ap_CS_fsm_state80;
wire   [63:0] grp_fu_179_p1;
reg   [63:0] conv_1_reg_414;
wire   [63:0] grp_fu_182_p1;
reg   [63:0] conv_2_reg_419;
wire    ap_CS_fsm_state81;
wire    ap_CS_fsm_state82;
wire    ap_CS_fsm_state83;
wire   [2:0] trunc_ln34_fu_324_p1;
reg   [2:0] trunc_ln34_reg_439;
wire   [39:0] grp_fu_317_p2;
reg   [39:0] mul_ln34_reg_444;
reg   [7:0] query_scores_address0;
reg    query_scores_ce0;
reg    query_scores_we0;
reg   [31:0] query_scores_d0;
wire   [31:0] query_scores_q0;
wire    grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_ap_start;
wire    grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_ap_done;
wire    grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_ap_idle;
wire    grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_ap_ready;
wire    grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_AWVALID;
wire   [63:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_AWADDR;
wire   [0:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_AWID;
wire   [31:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_AWLEN;
wire   [2:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_AWSIZE;
wire   [1:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_AWBURST;
wire   [1:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_AWLOCK;
wire   [3:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_AWCACHE;
wire   [2:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_AWPROT;
wire   [3:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_AWQOS;
wire   [3:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_AWREGION;
wire   [0:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_AWUSER;
wire    grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_WVALID;
wire   [63:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_WDATA;
wire   [7:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_WSTRB;
wire    grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_WLAST;
wire   [0:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_WID;
wire   [0:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_WUSER;
wire    grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_ARVALID;
wire   [63:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_ARADDR;
wire   [0:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_ARID;
wire   [31:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_ARLEN;
wire   [2:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_ARSIZE;
wire   [1:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_ARBURST;
wire   [1:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_ARLOCK;
wire   [3:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_ARCACHE;
wire   [2:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_ARPROT;
wire   [3:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_ARQOS;
wire   [3:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_ARREGION;
wire   [0:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_ARUSER;
wire    grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_RREADY;
wire    grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_BREADY;
wire   [7:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_query_scores_address0;
wire    grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_query_scores_ce0;
wire    grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_query_scores_we0;
wire   [31:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_query_scores_d0;
wire    grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_ap_start;
wire    grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_ap_done;
wire    grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_ap_idle;
wire    grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_ap_ready;
wire    grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_AWVALID;
wire   [63:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_AWADDR;
wire   [0:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_AWID;
wire   [31:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_AWLEN;
wire   [2:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_AWSIZE;
wire   [1:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_AWBURST;
wire   [1:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_AWLOCK;
wire   [3:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_AWCACHE;
wire   [2:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_AWPROT;
wire   [3:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_AWQOS;
wire   [3:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_AWREGION;
wire   [0:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_AWUSER;
wire    grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_WVALID;
wire   [63:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_WDATA;
wire   [7:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_WSTRB;
wire    grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_WLAST;
wire   [0:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_WID;
wire   [0:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_WUSER;
wire    grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_ARVALID;
wire   [63:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_ARADDR;
wire   [0:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_ARID;
wire   [31:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_ARLEN;
wire   [2:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_ARSIZE;
wire   [1:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_ARBURST;
wire   [1:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_ARLOCK;
wire   [3:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_ARCACHE;
wire   [2:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_ARPROT;
wire   [3:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_ARQOS;
wire   [3:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_ARREGION;
wire   [0:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_ARUSER;
wire    grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_RREADY;
wire    grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_BREADY;
wire   [7:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_query_scores_address0;
wire    grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_query_scores_ce0;
wire    grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_query_scores_we0;
wire   [31:0] grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_query_scores_d0;
reg    gmem_AWVALID;
wire    gmem_AWREADY;
reg    gmem_WVALID;
wire    gmem_WREADY;
reg    gmem_ARVALID;
wire    gmem_ARREADY;
reg   [63:0] gmem_ARADDR;
reg   [31:0] gmem_ARLEN;
wire    gmem_RVALID;
reg    gmem_RREADY;
wire   [63:0] gmem_RDATA;
wire   [8:0] gmem_RFIFONUM;
wire    gmem_BVALID;
reg    gmem_BREADY;
reg    grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_ap_start_reg;
reg    grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_ap_start_reg;
wire    ap_CS_fsm_state84;
wire  signed [63:0] sext_ln19_fu_199_p1;
wire  signed [63:0] sext_ln19_2_fu_239_p1;
wire  signed [63:0] sext_ln19_3_fu_249_p1;
reg    ap_block_state1;
wire    ap_CS_fsm_state76;
wire   [63:0] add_ln19_1_fu_209_p2;
wire   [63:0] add_ln19_fu_224_p2;
wire   [2:0] xor_ln19_fu_259_p2;
wire   [5:0] shl_ln19_2_fu_264_p3;
wire   [63:0] zext_ln19_1_fu_272_p1;
wire   [63:0] lshr_ln19_1_fu_276_p2;
wire   [5:0] shl_ln19_1_fu_285_p3;
wire   [63:0] zext_ln19_fu_292_p1;
wire   [63:0] lshr_ln19_fu_296_p2;
wire   [63:0] lshr_ln19_2_fu_305_p2;
wire   [31:0] grp_fu_317_p0;
wire   [8:0] grp_fu_317_p1;
reg    grp_fu_317_ce;
reg   [83:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
wire    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
wire    ap_ST_fsm_state53_blk;
wire    ap_ST_fsm_state54_blk;
wire    ap_ST_fsm_state55_blk;
wire    ap_ST_fsm_state56_blk;
wire    ap_ST_fsm_state57_blk;
wire    ap_ST_fsm_state58_blk;
wire    ap_ST_fsm_state59_blk;
wire    ap_ST_fsm_state60_blk;
wire    ap_ST_fsm_state61_blk;
wire    ap_ST_fsm_state62_blk;
wire    ap_ST_fsm_state63_blk;
wire    ap_ST_fsm_state64_blk;
wire    ap_ST_fsm_state65_blk;
wire    ap_ST_fsm_state66_blk;
wire    ap_ST_fsm_state67_blk;
wire    ap_ST_fsm_state68_blk;
wire    ap_ST_fsm_state69_blk;
wire    ap_ST_fsm_state70_blk;
wire    ap_ST_fsm_state71_blk;
reg    ap_ST_fsm_state72_blk;
reg    ap_ST_fsm_state73_blk;
reg    ap_ST_fsm_state74_blk;
wire    ap_ST_fsm_state75_blk;
wire    ap_ST_fsm_state76_blk;
wire    ap_ST_fsm_state77_blk;
wire    ap_ST_fsm_state78_blk;
wire    ap_ST_fsm_state79_blk;
wire    ap_ST_fsm_state80_blk;
wire    ap_ST_fsm_state81_blk;
reg    ap_ST_fsm_state82_blk;
wire    ap_ST_fsm_state83_blk;
reg    ap_ST_fsm_state84_blk;
wire   [39:0] grp_fu_317_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 84'd1;
#0 grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_ap_start_reg = 1'b0;
#0 grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_ap_start_reg = 1'b0;
end

topKQueryScores_query_scores_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 238 ),
    .AddressWidth( 8 ))
query_scores_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(query_scores_address0),
    .ce0(query_scores_ce0),
    .we0(query_scores_we0),
    .d0(query_scores_d0),
    .q0(query_scores_q0)
);

topKQueryScores_topKQueryScores_Pipeline_VITIS_LOOP_16_1 grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_ap_start),
    .ap_done(grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_ap_done),
    .ap_idle(grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_ap_idle),
    .ap_ready(grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_ap_ready),
    .m_axi_gmem_AWVALID(grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(gmem_RFIFONUM),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .fs_matrix(fs_matrix_read_reg_335),
    .conv(conv_reg_409),
    .conv_1(conv_1_reg_414),
    .conv_2(conv_2_reg_419),
    .query_scores_address0(grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_query_scores_address0),
    .query_scores_ce0(grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_query_scores_ce0),
    .query_scores_we0(grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_query_scores_we0),
    .query_scores_d0(grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_query_scores_d0)
);

topKQueryScores_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4 grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_ap_start),
    .ap_done(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_ap_done),
    .ap_idle(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_ap_idle),
    .ap_ready(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_ap_ready),
    .m_axi_gmem_AWVALID(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(gmem_AWREADY),
    .m_axi_gmem_AWADDR(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(gmem_WREADY),
    .m_axi_gmem_WDATA(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(1'b0),
    .m_axi_gmem_ARADDR(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(1'b0),
    .m_axi_gmem_RREADY(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(64'd0),
    .m_axi_gmem_RLAST(1'b0),
    .m_axi_gmem_RID(1'd0),
    .m_axi_gmem_RFIFONUM(9'd0),
    .m_axi_gmem_RUSER(1'd0),
    .m_axi_gmem_RRESP(2'd0),
    .m_axi_gmem_BVALID(gmem_BVALID),
    .m_axi_gmem_BREADY(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .mul_ln34(mul_ln34_reg_444),
    .query_scores_address0(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_query_scores_address0),
    .query_scores_ce0(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_query_scores_ce0),
    .query_scores_we0(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_query_scores_we0),
    .query_scores_d0(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_query_scores_d0),
    .query_scores_q0(query_scores_q0),
    .topK_indices(topK_indices),
    .trunc_ln34_1(trunc_ln34_reg_439)
);

topKQueryScores_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .fs_matrix(fs_matrix),
    .query_type(query_type),
    .k(k),
    .topK_indices(topK_indices),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_continue(ap_continue),
    .ap_idle(ap_idle)
);

topKQueryScores_gmem_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 69 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ),
    .USER_RFIFONUM_WIDTH( 9 ),
    .USER_DW( 64 ),
    .USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem_ARVALID),
    .I_ARREADY(gmem_ARREADY),
    .I_ARADDR(gmem_ARADDR),
    .I_ARLEN(gmem_ARLEN),
    .I_RVALID(gmem_RVALID),
    .I_RREADY(gmem_RREADY),
    .I_RDATA(gmem_RDATA),
    .I_RFIFONUM(gmem_RFIFONUM),
    .I_AWVALID(gmem_AWVALID),
    .I_AWREADY(gmem_AWREADY),
    .I_AWADDR(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_AWADDR),
    .I_AWLEN(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_AWLEN),
    .I_WVALID(gmem_WVALID),
    .I_WREADY(gmem_WREADY),
    .I_WDATA(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_WDATA),
    .I_WSTRB(grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_WSTRB),
    .I_BVALID(gmem_BVALID),
    .I_BREADY(gmem_BREADY)
);

topKQueryScores_sitodp_32ns_64_5_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
sitodp_32ns_64_5_no_dsp_1_U16(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(trunc_ln19_2_reg_399),
    .ce(1'b1),
    .dout(grp_fu_176_p1)
);

topKQueryScores_sitodp_32ns_64_5_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
sitodp_32ns_64_5_no_dsp_1_U17(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(trunc_ln19_3_reg_389),
    .ce(1'b1),
    .dout(grp_fu_179_p1)
);

topKQueryScores_sitodp_32ns_64_5_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
sitodp_32ns_64_5_no_dsp_1_U18(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(trunc_ln19_5_reg_404),
    .ce(1'b1),
    .dout(grp_fu_182_p1)
);

topKQueryScores_mul_32ns_9ns_40_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 40 ))
mul_32ns_9ns_40_2_1_U19(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_317_p0),
    .din1(grp_fu_317_p1),
    .ce(grp_fu_317_ce),
    .dout(grp_fu_317_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state84))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state81)) begin
            grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_ap_start_reg <= 1'b1;
        end else if ((grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_ap_ready == 1'b1)) begin
            grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state83)) begin
            grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_ap_start_reg <= 1'b1;
        end else if ((grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_ap_ready == 1'b1)) begin
            grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state80)) begin
        conv_1_reg_414 <= grp_fu_179_p1;
        conv_2_reg_419 <= grp_fu_182_p1;
        conv_reg_409 <= grp_fu_176_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        fs_matrix_read_reg_335 <= fs_matrix;
        query_type_read_reg_329 <= query_type;
        trunc_ln19_1_reg_346 <= {{query_type[63:3]}};
        trunc_ln19_reg_340 <= trunc_ln19_fu_185_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state73)) begin
        gmem_addr_3_read_reg_384 <= gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state74)) begin
        gmem_addr_4_read_reg_394 <= gmem_RDATA;
        trunc_ln19_3_reg_389 <= trunc_ln19_3_fu_281_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state72)) begin
        gmem_addr_read_reg_379 <= gmem_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state83)) begin
        mul_ln34_reg_444 <= grp_fu_317_p2;
        trunc_ln34_reg_439 <= trunc_ln34_fu_324_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state75)) begin
        trunc_ln19_2_reg_399 <= trunc_ln19_2_fu_301_p1;
        trunc_ln19_5_reg_404 <= trunc_ln19_5_fu_310_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        trunc_ln19_4_reg_357 <= {{add_ln19_1_fu_209_p2[63:3]}};
        trunc_ln19_7_reg_362 <= {{add_ln19_fu_224_p2[63:3]}};
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

always @ (*) begin
    if ((gmem_ARREADY == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

always @ (*) begin
    if ((gmem_ARREADY == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

always @ (*) begin
    if ((gmem_ARREADY == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

assign ap_ST_fsm_state54_blk = 1'b0;

assign ap_ST_fsm_state55_blk = 1'b0;

assign ap_ST_fsm_state56_blk = 1'b0;

assign ap_ST_fsm_state57_blk = 1'b0;

assign ap_ST_fsm_state58_blk = 1'b0;

assign ap_ST_fsm_state59_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state60_blk = 1'b0;

assign ap_ST_fsm_state61_blk = 1'b0;

assign ap_ST_fsm_state62_blk = 1'b0;

assign ap_ST_fsm_state63_blk = 1'b0;

assign ap_ST_fsm_state64_blk = 1'b0;

assign ap_ST_fsm_state65_blk = 1'b0;

assign ap_ST_fsm_state66_blk = 1'b0;

assign ap_ST_fsm_state67_blk = 1'b0;

assign ap_ST_fsm_state68_blk = 1'b0;

assign ap_ST_fsm_state69_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state70_blk = 1'b0;

assign ap_ST_fsm_state71_blk = 1'b0;

always @ (*) begin
    if ((gmem_RVALID == 1'b0)) begin
        ap_ST_fsm_state72_blk = 1'b1;
    end else begin
        ap_ST_fsm_state72_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_RVALID == 1'b0)) begin
        ap_ST_fsm_state73_blk = 1'b1;
    end else begin
        ap_ST_fsm_state73_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_RVALID == 1'b0)) begin
        ap_ST_fsm_state74_blk = 1'b1;
    end else begin
        ap_ST_fsm_state74_blk = 1'b0;
    end
end

assign ap_ST_fsm_state75_blk = 1'b0;

assign ap_ST_fsm_state76_blk = 1'b0;

assign ap_ST_fsm_state77_blk = 1'b0;

assign ap_ST_fsm_state78_blk = 1'b0;

assign ap_ST_fsm_state79_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state80_blk = 1'b0;

assign ap_ST_fsm_state81_blk = 1'b0;

always @ (*) begin
    if ((grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_ap_done == 1'b0)) begin
        ap_ST_fsm_state82_blk = 1'b1;
    end else begin
        ap_ST_fsm_state82_blk = 1'b0;
    end
end

assign ap_ST_fsm_state83_blk = 1'b0;

always @ (*) begin
    if ((grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_ap_done == 1'b0)) begin
        ap_ST_fsm_state84_blk = 1'b1;
    end else begin
        ap_ST_fsm_state84_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state84))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state84))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        gmem_ARADDR = sext_ln19_3_fu_249_p1;
    end else if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        gmem_ARADDR = sext_ln19_2_fu_239_p1;
    end else if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        gmem_ARADDR = sext_ln19_fu_199_p1;
    end else if (((1'b1 == ap_CS_fsm_state82) | (1'b1 == ap_CS_fsm_state81))) begin
        gmem_ARADDR = grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_ARADDR;
    end else begin
        gmem_ARADDR = 'bx;
    end
end

always @ (*) begin
    if ((((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state4)) | ((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3)) | ((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        gmem_ARLEN = 32'd1;
    end else if (((1'b1 == ap_CS_fsm_state82) | (1'b1 == ap_CS_fsm_state81))) begin
        gmem_ARLEN = grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_ARLEN;
    end else begin
        gmem_ARLEN = 'bx;
    end
end

always @ (*) begin
    if ((((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state4)) | ((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3)) | ((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        gmem_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state82) | (1'b1 == ap_CS_fsm_state81))) begin
        gmem_ARVALID = grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_ARVALID;
    end else begin
        gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state84) | (1'b1 == ap_CS_fsm_state83))) begin
        gmem_AWVALID = grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_AWVALID;
    end else begin
        gmem_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state84) | (1'b1 == ap_CS_fsm_state83))) begin
        gmem_BREADY = grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_BREADY;
    end else begin
        gmem_BREADY = 1'b0;
    end
end

always @ (*) begin
    if ((((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state74)) | ((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state73)) | ((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state72)))) begin
        gmem_RREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state82) | (1'b1 == ap_CS_fsm_state81))) begin
        gmem_RREADY = grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_m_axi_gmem_RREADY;
    end else begin
        gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state84) | (1'b1 == ap_CS_fsm_state83))) begin
        gmem_WVALID = grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_m_axi_gmem_WVALID;
    end else begin
        gmem_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state74) | (1'b1 == ap_CS_fsm_state73) | (1'b1 == ap_CS_fsm_state72))) begin
        gmem_blk_n_R = m_axi_gmem_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state83) | ((grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state82)))) begin
        grp_fu_317_ce = 1'b1;
    end else begin
        grp_fu_317_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state84)) begin
        query_scores_address0 = grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_query_scores_address0;
    end else if ((1'b1 == ap_CS_fsm_state82)) begin
        query_scores_address0 = grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_query_scores_address0;
    end else begin
        query_scores_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state84)) begin
        query_scores_ce0 = grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_query_scores_ce0;
    end else if ((1'b1 == ap_CS_fsm_state82)) begin
        query_scores_ce0 = grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_query_scores_ce0;
    end else begin
        query_scores_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state84)) begin
        query_scores_d0 = grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_query_scores_d0;
    end else if ((1'b1 == ap_CS_fsm_state82)) begin
        query_scores_d0 = grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_query_scores_d0;
    end else begin
        query_scores_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state84)) begin
        query_scores_we0 = grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_query_scores_we0;
    end else if ((1'b1 == ap_CS_fsm_state82)) begin
        query_scores_we0 = grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_query_scores_we0;
    end else begin
        query_scores_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            if (((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state72))) begin
                ap_NS_fsm = ap_ST_fsm_state73;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state72;
            end
        end
        ap_ST_fsm_state73 : begin
            if (((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state73))) begin
                ap_NS_fsm = ap_ST_fsm_state74;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state73;
            end
        end
        ap_ST_fsm_state74 : begin
            if (((gmem_RVALID == 1'b1) & (1'b1 == ap_CS_fsm_state74))) begin
                ap_NS_fsm = ap_ST_fsm_state75;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state74;
            end
        end
        ap_ST_fsm_state75 : begin
            ap_NS_fsm = ap_ST_fsm_state76;
        end
        ap_ST_fsm_state76 : begin
            ap_NS_fsm = ap_ST_fsm_state77;
        end
        ap_ST_fsm_state77 : begin
            ap_NS_fsm = ap_ST_fsm_state78;
        end
        ap_ST_fsm_state78 : begin
            ap_NS_fsm = ap_ST_fsm_state79;
        end
        ap_ST_fsm_state79 : begin
            ap_NS_fsm = ap_ST_fsm_state80;
        end
        ap_ST_fsm_state80 : begin
            ap_NS_fsm = ap_ST_fsm_state81;
        end
        ap_ST_fsm_state81 : begin
            ap_NS_fsm = ap_ST_fsm_state82;
        end
        ap_ST_fsm_state82 : begin
            if (((grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state82))) begin
                ap_NS_fsm = ap_ST_fsm_state83;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state82;
            end
        end
        ap_ST_fsm_state83 : begin
            ap_NS_fsm = ap_ST_fsm_state84;
        end
        ap_ST_fsm_state84 : begin
            if (((grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state84))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state84;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln19_1_fu_209_p2 = (query_type_read_reg_329 + 64'd4);

assign add_ln19_fu_224_p2 = (query_type_read_reg_329 + 64'd8);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state72 = ap_CS_fsm[32'd71];

assign ap_CS_fsm_state73 = ap_CS_fsm[32'd72];

assign ap_CS_fsm_state74 = ap_CS_fsm[32'd73];

assign ap_CS_fsm_state75 = ap_CS_fsm[32'd74];

assign ap_CS_fsm_state76 = ap_CS_fsm[32'd75];

assign ap_CS_fsm_state80 = ap_CS_fsm[32'd79];

assign ap_CS_fsm_state81 = ap_CS_fsm[32'd80];

assign ap_CS_fsm_state82 = ap_CS_fsm[32'd81];

assign ap_CS_fsm_state83 = ap_CS_fsm[32'd82];

assign ap_CS_fsm_state84 = ap_CS_fsm[32'd83];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

assign grp_fu_317_p0 = grp_fu_317_p00;

assign grp_fu_317_p00 = k;

assign grp_fu_317_p1 = 40'd238;

assign grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_ap_start = grp_topKQueryScores_Pipeline_VITIS_LOOP_16_1_fu_154_ap_start_reg;

assign grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_ap_start = grp_topKQueryScores_Pipeline_VITIS_LOOP_24_3_VITIS_LOOP_27_4_fu_165_ap_start_reg;

assign lshr_ln19_1_fu_276_p2 = gmem_addr_3_read_reg_384 >> zext_ln19_1_fu_272_p1;

assign lshr_ln19_2_fu_305_p2 = gmem_addr_4_read_reg_394 >> zext_ln19_fu_292_p1;

assign lshr_ln19_fu_296_p2 = gmem_addr_read_reg_379 >> zext_ln19_fu_292_p1;

assign sext_ln19_2_fu_239_p1 = $signed(trunc_ln19_4_reg_357);

assign sext_ln19_3_fu_249_p1 = $signed(trunc_ln19_7_reg_362);

assign sext_ln19_fu_199_p1 = $signed(trunc_ln19_1_reg_346);

assign shl_ln19_1_fu_285_p3 = {{trunc_ln19_reg_340}, {3'd0}};

assign shl_ln19_2_fu_264_p3 = {{xor_ln19_fu_259_p2}, {3'd0}};

assign trunc_ln19_2_fu_301_p1 = lshr_ln19_fu_296_p2[31:0];

assign trunc_ln19_3_fu_281_p1 = lshr_ln19_1_fu_276_p2[31:0];

assign trunc_ln19_5_fu_310_p1 = lshr_ln19_2_fu_305_p2[31:0];

assign trunc_ln19_fu_185_p1 = query_type[2:0];

assign trunc_ln34_fu_324_p1 = topK_indices[2:0];

assign xor_ln19_fu_259_p2 = (trunc_ln19_reg_340 ^ 3'd4);

assign zext_ln19_1_fu_272_p1 = shl_ln19_2_fu_264_p3;

assign zext_ln19_fu_292_p1 = shl_ln19_1_fu_285_p3;

endmodule //topKQueryScores
