# This file was automatically generated by Vpl
if { ![info exists _is_init_cmds] } {
  set script_old $::optrace::script
  set category_old $::optrace::category
  source ../../../ipirun.tcl
  variable ::optrace::script $script_old
  variable ::optrace::category $category_old
  source $local_dir/debug_profile_hooks.tcl
  namespace import ocl_util::*

set VPL_ERROR_LOGGED 707
  set _is_init_cmds true
}


ocl_util::report_utilization_drc "luts 1488120 brams 2384 registers 2976240 dsps 10634" "level0_i/level1/level1_i/ulp" 0.8 $steps_log $vivado_output_dir
