# This file was automatically generated by Vpl
# utilization reports
report_utilization_impl true "topKQueryScores" "placed" "level0_i/level1/level1_i/ulp" $input_dir $vivado_output_dir
collect_compute_unit_utilization "level0_i/level1/level1_i/ulp"
