# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_0/ip/ip_23/bd_b35e_rs_M00_AXI_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_b35e_rs_M00_AXI_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_0/ip/ip_23/bd_b35e_rs_M00_AXI_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_b35e_rs_M00_AXI_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_0/ip/ip_23/bd_b35e_rs_M00_AXI_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_b35e_rs_M00_AXI_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_memory_subsystem_0/bd_0/ip/ip_23/bd_b35e_rs_M00_AXI_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_b35e_rs_M00_AXI_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
