# This file was automatically generated by vpl.
# To open the vivado project generated by vpl, run the following command
# vivado -source openprj.tcl

puts "--- DEBUG: source .local/hw_platform/tcl_hooks/pre_create_project.tcl"
source .local/hw_platform/tcl_hooks/pre_create_project.tcl
puts "--- DEBUG: source scripts/_vivado_params.tcl"
source scripts/_vivado_params.tcl
open_project prj/prj.xpr
