# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.srcs/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/ulp_ii_level1_wire_0.xci
# IP: The module: 'ulp_ii_level1_wire_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/src/ii_level1_wire_pxi_ii_core_0/ii_level1_wire_pxi_ii_core_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ii_level1_wire_pxi_ii_core_0 || ORIG_REF_NAME==ii_level1_wire_pxi_ii_core_0} -quiet] -quiet

# Block Designs: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/bd_1860.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860 || ORIG_REF_NAME==bd_1860} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_0/bd_1860_ip_aclk_ctrl_00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_ip_aclk_ctrl_00_0 || ORIG_REF_NAME==bd_1860_ip_aclk_ctrl_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_1/bd_1860_ip_aclk_pcie_user_00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_ip_aclk_pcie_user_00_0 || ORIG_REF_NAME==bd_1860_ip_aclk_pcie_user_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_2/bd_1860_ip_aclk_freerun_ref_00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_ip_aclk_freerun_ref_00_0 || ORIG_REF_NAME==bd_1860_ip_aclk_freerun_ref_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_3/bd_1860_ip_aclk_data_u2s_00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_ip_aclk_data_u2s_00_0 || ORIG_REF_NAME==bd_1860_ip_aclk_data_u2s_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_4/bd_1860_ip_aresetn_ctrl_00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_ip_aresetn_ctrl_00_0 || ORIG_REF_NAME==bd_1860_ip_aresetn_ctrl_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_5/bd_1860_ip_aresetn_pcie_user_00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_ip_aresetn_pcie_user_00_0 || ORIG_REF_NAME==bd_1860_ip_aresetn_pcie_user_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_6/bd_1860_ip_aresetn_data_u2s_00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_ip_aresetn_data_u2s_00_0 || ORIG_REF_NAME==bd_1860_ip_aresetn_data_u2s_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_7/bd_1860_s_ip_axi_ctrl_mgmt_00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_ctrl_mgmt_00_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_ctrl_mgmt_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_8/bd_1860_m_ip_axi_ctrl_mgmt_00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_ctrl_mgmt_00_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_ctrl_mgmt_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_9/bd_1860_s_ip_axi_ctrl_mgmt_01_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_ctrl_mgmt_01_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_ctrl_mgmt_01_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_10/bd_1860_m_ip_axi_ctrl_mgmt_01_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_ctrl_mgmt_01_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_ctrl_mgmt_01_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_11/bd_1860_s_ip_axi_ctrl_user_00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_ctrl_user_00_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_ctrl_user_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_12/bd_1860_m_ip_axi_ctrl_user_00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_ctrl_user_00_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_ctrl_user_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_13/bd_1860_s_ip_axi_ctrl_user_01_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_ctrl_user_01_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_ctrl_user_01_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_14/bd_1860_m_ip_axi_ctrl_user_01_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_ctrl_user_01_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_ctrl_user_01_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_15/bd_1860_s_ip_axi_ctrl_user_02_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_ctrl_user_02_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_ctrl_user_02_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_16/bd_1860_m_ip_axi_ctrl_user_02_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_ctrl_user_02_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_ctrl_user_02_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_17/bd_1860_s_ip_axi_ctrl_user_03_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_ctrl_user_03_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_ctrl_user_03_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_18/bd_1860_m_ip_axi_ctrl_user_03_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_ctrl_user_03_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_ctrl_user_03_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_19/bd_1860_s_ip_axi_ctrl_user_debug_00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_ctrl_user_debug_00_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_ctrl_user_debug_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_20/bd_1860_m_ip_axi_ctrl_user_debug_00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_ctrl_user_debug_00_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_ctrl_user_debug_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_21/bd_1860_s_ip_axi_data_c2h_00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_data_c2h_00_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_data_c2h_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_22/bd_1860_m_ip_axi_data_c2h_00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_data_c2h_00_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_data_c2h_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_23/bd_1860_s_ip_axi_data_h2c_00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_data_h2c_00_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_data_h2c_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_24/bd_1860_m_ip_axi_data_h2c_00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_data_h2c_00_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_data_h2c_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_25/bd_1860_s_ip_axi_data_h2c_01_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_data_h2c_01_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_data_h2c_01_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_26/bd_1860_m_ip_axi_data_h2c_01_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_data_h2c_01_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_data_h2c_01_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_27/bd_1860_s_ip_axi_data_h2c_02_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_data_h2c_02_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_data_h2c_02_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_28/bd_1860_m_ip_axi_data_h2c_02_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_data_h2c_02_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_data_h2c_02_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_29/bd_1860_s_ip_axi_data_h2c_03_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_data_h2c_03_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_data_h2c_03_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_30/bd_1860_m_ip_axi_data_h2c_03_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_data_h2c_03_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_data_h2c_03_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_31/bd_1860_s_ip_axi_data_u2s_00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_data_u2s_00_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_data_u2s_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_32/bd_1860_m_ip_axi_data_u2s_00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_data_u2s_00_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_data_u2s_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_33/bd_1860_ip_data_ddr4_calib_complete_00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_ip_data_ddr4_calib_complete_00_0 || ORIG_REF_NAME==bd_1860_ip_data_ddr4_calib_complete_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_34/bd_1860_ip_data_satellite_ctrl_data_00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_ip_data_satellite_ctrl_data_00_0 || ORIG_REF_NAME==bd_1860_ip_data_satellite_ctrl_data_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_35/bd_1860_ip_irq_kernel_00_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_ip_irq_kernel_00_0 || ORIG_REF_NAME==bd_1860_ip_irq_kernel_00_0} -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_7/bd_1860_s_ip_axi_ctrl_mgmt_00_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_ctrl_mgmt_00_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_ctrl_mgmt_00_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_8/bd_1860_m_ip_axi_ctrl_mgmt_00_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_ctrl_mgmt_00_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_ctrl_mgmt_00_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_9/bd_1860_s_ip_axi_ctrl_mgmt_01_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_ctrl_mgmt_01_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_ctrl_mgmt_01_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_10/bd_1860_m_ip_axi_ctrl_mgmt_01_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_ctrl_mgmt_01_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_ctrl_mgmt_01_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_11/bd_1860_s_ip_axi_ctrl_user_00_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_ctrl_user_00_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_ctrl_user_00_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_12/bd_1860_m_ip_axi_ctrl_user_00_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_ctrl_user_00_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_ctrl_user_00_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_13/bd_1860_s_ip_axi_ctrl_user_01_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_ctrl_user_01_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_ctrl_user_01_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_14/bd_1860_m_ip_axi_ctrl_user_01_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_ctrl_user_01_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_ctrl_user_01_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_15/bd_1860_s_ip_axi_ctrl_user_02_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_ctrl_user_02_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_ctrl_user_02_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_16/bd_1860_m_ip_axi_ctrl_user_02_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_ctrl_user_02_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_ctrl_user_02_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_17/bd_1860_s_ip_axi_ctrl_user_03_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_ctrl_user_03_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_ctrl_user_03_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_18/bd_1860_m_ip_axi_ctrl_user_03_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_ctrl_user_03_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_ctrl_user_03_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_19/bd_1860_s_ip_axi_ctrl_user_debug_00_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_ctrl_user_debug_00_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_ctrl_user_debug_00_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_20/bd_1860_m_ip_axi_ctrl_user_debug_00_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_ctrl_user_debug_00_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_ctrl_user_debug_00_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_21/bd_1860_s_ip_axi_data_c2h_00_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_data_c2h_00_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_data_c2h_00_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_22/bd_1860_m_ip_axi_data_c2h_00_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_data_c2h_00_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_data_c2h_00_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_23/bd_1860_s_ip_axi_data_h2c_00_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_data_h2c_00_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_data_h2c_00_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_24/bd_1860_m_ip_axi_data_h2c_00_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_data_h2c_00_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_data_h2c_00_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_25/bd_1860_s_ip_axi_data_h2c_01_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_data_h2c_01_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_data_h2c_01_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_26/bd_1860_m_ip_axi_data_h2c_01_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_data_h2c_01_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_data_h2c_01_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_27/bd_1860_s_ip_axi_data_h2c_02_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_data_h2c_02_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_data_h2c_02_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_28/bd_1860_m_ip_axi_data_h2c_02_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_data_h2c_02_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_data_h2c_02_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_29/bd_1860_s_ip_axi_data_h2c_03_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_data_h2c_03_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_data_h2c_03_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_30/bd_1860_m_ip_axi_data_h2c_03_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_data_h2c_03_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_data_h2c_03_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_31/bd_1860_s_ip_axi_data_u2s_00_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_data_u2s_00_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_data_u2s_00_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_32/bd_1860_m_ip_axi_data_u2s_00_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_data_u2s_00_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_data_u2s_00_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/bd_1860_ooc.xdc

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/src/ii_level1_wire_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp_ii_level1_wire_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/uuid_stamp.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp_ii_level1_wire_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.srcs/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/ulp_ii_level1_wire_0.xci
# IP: The module: 'ulp_ii_level1_wire_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/src/ii_level1_wire_pxi_ii_core_0/ii_level1_wire_pxi_ii_core_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ii_level1_wire_pxi_ii_core_0 || ORIG_REF_NAME==ii_level1_wire_pxi_ii_core_0} -quiet] -quiet

# Block Designs: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/bd_1860.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860 || ORIG_REF_NAME==bd_1860} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_0/bd_1860_ip_aclk_ctrl_00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_ip_aclk_ctrl_00_0 || ORIG_REF_NAME==bd_1860_ip_aclk_ctrl_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_1/bd_1860_ip_aclk_pcie_user_00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_ip_aclk_pcie_user_00_0 || ORIG_REF_NAME==bd_1860_ip_aclk_pcie_user_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_2/bd_1860_ip_aclk_freerun_ref_00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_ip_aclk_freerun_ref_00_0 || ORIG_REF_NAME==bd_1860_ip_aclk_freerun_ref_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_3/bd_1860_ip_aclk_data_u2s_00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_ip_aclk_data_u2s_00_0 || ORIG_REF_NAME==bd_1860_ip_aclk_data_u2s_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_4/bd_1860_ip_aresetn_ctrl_00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_ip_aresetn_ctrl_00_0 || ORIG_REF_NAME==bd_1860_ip_aresetn_ctrl_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_5/bd_1860_ip_aresetn_pcie_user_00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_ip_aresetn_pcie_user_00_0 || ORIG_REF_NAME==bd_1860_ip_aresetn_pcie_user_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_6/bd_1860_ip_aresetn_data_u2s_00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_ip_aresetn_data_u2s_00_0 || ORIG_REF_NAME==bd_1860_ip_aresetn_data_u2s_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_7/bd_1860_s_ip_axi_ctrl_mgmt_00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_ctrl_mgmt_00_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_ctrl_mgmt_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_8/bd_1860_m_ip_axi_ctrl_mgmt_00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_ctrl_mgmt_00_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_ctrl_mgmt_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_9/bd_1860_s_ip_axi_ctrl_mgmt_01_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_ctrl_mgmt_01_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_ctrl_mgmt_01_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_10/bd_1860_m_ip_axi_ctrl_mgmt_01_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_ctrl_mgmt_01_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_ctrl_mgmt_01_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_11/bd_1860_s_ip_axi_ctrl_user_00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_ctrl_user_00_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_ctrl_user_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_12/bd_1860_m_ip_axi_ctrl_user_00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_ctrl_user_00_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_ctrl_user_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_13/bd_1860_s_ip_axi_ctrl_user_01_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_ctrl_user_01_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_ctrl_user_01_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_14/bd_1860_m_ip_axi_ctrl_user_01_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_ctrl_user_01_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_ctrl_user_01_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_15/bd_1860_s_ip_axi_ctrl_user_02_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_ctrl_user_02_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_ctrl_user_02_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_16/bd_1860_m_ip_axi_ctrl_user_02_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_ctrl_user_02_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_ctrl_user_02_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_17/bd_1860_s_ip_axi_ctrl_user_03_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_ctrl_user_03_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_ctrl_user_03_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_18/bd_1860_m_ip_axi_ctrl_user_03_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_ctrl_user_03_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_ctrl_user_03_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_19/bd_1860_s_ip_axi_ctrl_user_debug_00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_ctrl_user_debug_00_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_ctrl_user_debug_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_20/bd_1860_m_ip_axi_ctrl_user_debug_00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_ctrl_user_debug_00_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_ctrl_user_debug_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_21/bd_1860_s_ip_axi_data_c2h_00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_data_c2h_00_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_data_c2h_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_22/bd_1860_m_ip_axi_data_c2h_00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_data_c2h_00_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_data_c2h_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_23/bd_1860_s_ip_axi_data_h2c_00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_data_h2c_00_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_data_h2c_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_24/bd_1860_m_ip_axi_data_h2c_00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_data_h2c_00_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_data_h2c_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_25/bd_1860_s_ip_axi_data_h2c_01_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_data_h2c_01_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_data_h2c_01_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_26/bd_1860_m_ip_axi_data_h2c_01_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_data_h2c_01_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_data_h2c_01_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_27/bd_1860_s_ip_axi_data_h2c_02_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_data_h2c_02_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_data_h2c_02_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_28/bd_1860_m_ip_axi_data_h2c_02_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_data_h2c_02_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_data_h2c_02_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_29/bd_1860_s_ip_axi_data_h2c_03_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_data_h2c_03_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_data_h2c_03_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_30/bd_1860_m_ip_axi_data_h2c_03_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_data_h2c_03_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_data_h2c_03_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_31/bd_1860_s_ip_axi_data_u2s_00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_data_u2s_00_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_data_u2s_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_32/bd_1860_m_ip_axi_data_u2s_00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_data_u2s_00_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_data_u2s_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_33/bd_1860_ip_data_ddr4_calib_complete_00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_ip_data_ddr4_calib_complete_00_0 || ORIG_REF_NAME==bd_1860_ip_data_ddr4_calib_complete_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_34/bd_1860_ip_data_satellite_ctrl_data_00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_ip_data_satellite_ctrl_data_00_0 || ORIG_REF_NAME==bd_1860_ip_data_satellite_ctrl_data_00_0} -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_35/bd_1860_ip_irq_kernel_00_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_1860_ip_irq_kernel_00_0 || ORIG_REF_NAME==bd_1860_ip_irq_kernel_00_0} -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_7/bd_1860_s_ip_axi_ctrl_mgmt_00_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_ctrl_mgmt_00_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_ctrl_mgmt_00_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_8/bd_1860_m_ip_axi_ctrl_mgmt_00_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_ctrl_mgmt_00_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_ctrl_mgmt_00_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_9/bd_1860_s_ip_axi_ctrl_mgmt_01_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_ctrl_mgmt_01_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_ctrl_mgmt_01_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_10/bd_1860_m_ip_axi_ctrl_mgmt_01_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_ctrl_mgmt_01_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_ctrl_mgmt_01_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_11/bd_1860_s_ip_axi_ctrl_user_00_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_ctrl_user_00_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_ctrl_user_00_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_12/bd_1860_m_ip_axi_ctrl_user_00_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_ctrl_user_00_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_ctrl_user_00_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_13/bd_1860_s_ip_axi_ctrl_user_01_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_ctrl_user_01_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_ctrl_user_01_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_14/bd_1860_m_ip_axi_ctrl_user_01_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_ctrl_user_01_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_ctrl_user_01_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_15/bd_1860_s_ip_axi_ctrl_user_02_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_ctrl_user_02_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_ctrl_user_02_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_16/bd_1860_m_ip_axi_ctrl_user_02_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_ctrl_user_02_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_ctrl_user_02_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_17/bd_1860_s_ip_axi_ctrl_user_03_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_ctrl_user_03_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_ctrl_user_03_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_18/bd_1860_m_ip_axi_ctrl_user_03_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_ctrl_user_03_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_ctrl_user_03_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_19/bd_1860_s_ip_axi_ctrl_user_debug_00_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_ctrl_user_debug_00_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_ctrl_user_debug_00_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_20/bd_1860_m_ip_axi_ctrl_user_debug_00_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_ctrl_user_debug_00_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_ctrl_user_debug_00_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_21/bd_1860_s_ip_axi_data_c2h_00_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_data_c2h_00_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_data_c2h_00_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_22/bd_1860_m_ip_axi_data_c2h_00_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_data_c2h_00_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_data_c2h_00_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_23/bd_1860_s_ip_axi_data_h2c_00_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_data_h2c_00_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_data_h2c_00_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_24/bd_1860_m_ip_axi_data_h2c_00_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_data_h2c_00_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_data_h2c_00_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_25/bd_1860_s_ip_axi_data_h2c_01_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_data_h2c_01_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_data_h2c_01_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_26/bd_1860_m_ip_axi_data_h2c_01_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_data_h2c_01_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_data_h2c_01_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_27/bd_1860_s_ip_axi_data_h2c_02_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_data_h2c_02_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_data_h2c_02_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_28/bd_1860_m_ip_axi_data_h2c_02_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_data_h2c_02_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_data_h2c_02_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_29/bd_1860_s_ip_axi_data_h2c_03_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_data_h2c_03_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_data_h2c_03_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_30/bd_1860_m_ip_axi_data_h2c_03_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_data_h2c_03_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_data_h2c_03_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_31/bd_1860_s_ip_axi_data_u2s_00_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_s_ip_axi_data_u2s_00_0 || ORIG_REF_NAME==bd_1860_s_ip_axi_data_u2s_00_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/ip/ip_32/bd_1860_m_ip_axi_data_u2s_00_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_1860_m_ip_axi_data_u2s_00_0 || ORIG_REF_NAME==bd_1860_m_ip_axi_data_u2s_00_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/bd_0/bd_1860_ooc.xdc

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/src/ii_level1_wire_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp_ii_level1_wire_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ii_level1_wire_0/uuid_stamp.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp_ii_level1_wire_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
