# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.srcs/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_00_slr0_0/ulp_ip_psr_aresetn_kernel_00_slr0_0.xci
# IP: The module: 'ulp_ip_psr_aresetn_kernel_00_slr0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_00_slr0_0/ulp_ip_psr_aresetn_kernel_00_slr0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp_ip_psr_aresetn_kernel_00_slr0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_00_slr0_0/ulp_ip_psr_aresetn_kernel_00_slr0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp_ip_psr_aresetn_kernel_00_slr0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_00_slr0_0/ulp_ip_psr_aresetn_kernel_00_slr0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp_ip_psr_aresetn_kernel_00_slr0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_00_slr0_0/ulp_ip_psr_aresetn_kernel_00_slr0_0_slr.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp_ip_psr_aresetn_kernel_00_slr0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.srcs/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_00_slr0_0/ulp_ip_psr_aresetn_kernel_00_slr0_0.xci
# IP: The module: 'ulp_ip_psr_aresetn_kernel_00_slr0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_00_slr0_0/ulp_ip_psr_aresetn_kernel_00_slr0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp_ip_psr_aresetn_kernel_00_slr0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_00_slr0_0/ulp_ip_psr_aresetn_kernel_00_slr0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp_ip_psr_aresetn_kernel_00_slr0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_00_slr0_0/ulp_ip_psr_aresetn_kernel_00_slr0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp_ip_psr_aresetn_kernel_00_slr0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/nmath018/topK_feature/hls_catch22/_x.hw.xilinx_u250_gen3x16_xdma_4_1_202210_1/link/vivado/vpl/prj/prj.gen/my_rm/bd/ulp/ip/ulp_ip_psr_aresetn_kernel_00_slr0_0/ulp_ip_psr_aresetn_kernel_00_slr0_0_slr.xdc
# XDC: The top module name and the constraint reference have the same name: 'ulp_ip_psr_aresetn_kernel_00_slr0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
